<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use dmstr\helpers\Html;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\ConfigSearch $searchModel
 */

$this->title = 'Config';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
</p>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{pager}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            \app\components\ActionButton::getButtons([
                                'template' => '{edit-value} {update}',
                                'buttons' => [
                                    'edit-value' => function ($url, $model, $key) {
                                        return Html::a('<i class="fa fa-gear"></i>', ['edit-value', 'id' => $model->id], ['class' => 'btn btn-primary mb-1 mr-1', 'title' => 'Edit Nilai']);
                                    },
                                ]
                            ]),

                            [
                                'attribute' => 'name',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'type',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'attribute',
                                'format' => 'ntext',
                            ],
                            [
                                'attribute' => 'value_parser',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'value',
                                'format' => 'ntext',
                                'filter' => false,
                            ],
                            // [
                            //     'attribute' => 'is_active',
                            //     'format' => 'boolean',
                            // ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>