<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;
use richardfan\widget\JSRegister;

/**
 * @var yii\web\View $this
 * @var app\models\SiteSetting $model
 * @var app\components\annex\ActiveForm $form
 */
$this->registerJsFile(Yii::getAlias("@web/tinymce/tinymce.min.js"));
$this->registerCssFile(Yii::getAlias("@web/homepage/css/accordion.css"));
// $uploadlink = Url::to(['site/upload-image']);
// $csrf = Yii::$app->request->csrfToken;

$this->registerJs("
      tinymce.init({
        selector: '.tinymce-form',
        height: '400',
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste code help wordcount',
        ],

        toolbar: 'undo redo | formatselect | ' +
        'bold italic backcolor | alignleft aligncenter ' +
        'alignright alignjustify | bullist numlist outdent indent | ' +
        'removeformat | help',
      });
");
?>

<?php $form = ActiveForm::begin([
    'id' => 'SiteSetting',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div id="aspect-content">
    <div class="aspect-tab ">
        <input id="item-18" type="checkbox" class="aspect-input" name="aspect">
        <label for="item-18" class="aspect-label"></label>
        <div class="aspect-content">
            <div class="aspect-info">
                <h4 class="aspect-name">Informasi Umum</h4>
            </div>
        </div>
        <div class="aspect-tab-content">
            <div class="row pt-3">
                <?= $form->field($model, 'judul', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'tagline', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'tagline2', \app\components\Constant::COLUMN(3))->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'no_telp', \app\components\Constant::COLUMN(3))->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'batas_pembayaran', \app\components\Constant::COLUMN(3))->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'tentang_web', \app\components\Constant::COLUMN(1))->textArea(['maxlength' => true, 'rows' => 15, 'class' => 'tinymce-form form-control']) ?>
                <?= $form->field($model, 'syarat_ketentuan', \app\components\Constant::COLUMN(1))->textArea(['maxlength' => true, 'rows' => 15, 'class' => 'tinymce-form form-control']) ?>
                <?= $form->field($model, 'kebijakan_dan_privacy', \app\components\Constant::COLUMN(1))->textArea(['maxlength' => true, 'rows' => 15, 'class' => 'tinymce-form form-control']) ?>
            </div>
        </div>
    </div>
    <div class="aspect-tab ">
        <input id="item-14" type="checkbox" class="aspect-input" name="aspect">
        <label for="item-14" class="aspect-label"></label>
        <div class="aspect-content">
            <div class="aspect-info">
                <h4 class="aspect-name">Kontak & Media Sosial</h4>
            </div>
        </div>
        <div class="aspect-tab-content">
            <div class="row pt-3">
                <?= $form->field($model, 'alamat', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'email', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'facebook', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'twitter', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'instagram', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'youtube', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'tiktok', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
                <?= $form->field($model, 'playstore', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
            </div>
        </div>
    </div>
    <div class="aspect-tab ">
        <input id="item-2" type="checkbox" class="aspect-input" name="aspect">
        <label for="item-2" class="aspect-label"></label>
        <div class="aspect-content">
            <div class="aspect-info">
                <h4 class="aspect-name">Logo & Gambar</h4>
            </div>
        </div>
        <div class="aspect-tab-content">
            <div class="row pt-3">
                <?= fieldUploaImage($model, $form, "logo", ["with_preview" => true, "column" => 2]) ?>
                <?= fieldUploaImage($model, $form, "logo_putih", ["with_preview" => true, "column" => 2]) ?>
                <?= fieldUploaImage($model, $form, "icon", ["with_preview" => true, "column" => 2]) ?>
                <?= fieldUploaImage($model, $form, "gambar_header", ["with_preview" => true, "column" => 2]) ?>
                <?= fieldUploaImage($model, $form, "gambar_login", ["with_preview" => true, "column" => 1]) ?>
                <?= $form->field(
                    $model,
                    'contoh_boq_proyek',
                    \app\components\Constant::COLUMN(2)
                )->widget(\kartik\file\FileInput::class, [
                    // 'options' => ['accept' => 'image/*'],
                    'pluginOptions' => [
                        'allowedFileExtensions' => ['doc', 'pdf', 'xlsx', 'xsl', 'csv'],
                    ],
                ]) ?>
                <?= $form->field(
                    $model,
                    'contoh_import_excel',
                    \app\components\Constant::COLUMN(2)
                )->widget(\kartik\file\FileInput::class, [
                    // 'options' => ['accept' => 'image/*'],
                    'pluginOptions' => [
                        'allowedFileExtensions' => ['xlsx', 'xsl', 'csv'],
                    ],
                ]) ?>
                <div class="col-6 text-center mb-3">
                    <?php
                    if ($model->contoh_boq_proyek != null) {
                        echo Yii::$app->formatter->asDownload($model->contoh_boq_proyek);
                    }
                    ?>
                </div>
                <div class="col-6 text-center mb-3">
                    <?php
                    if ($model->contoh_import_excel != null) {
                        echo Yii::$app->formatter->asDownload($model->contoh_import_excel);
                    }
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row mt-5">
    <div class="col-12 text-center">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>

<?php ActiveForm::end(); ?>