<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;
use kartik\depdrop\DepDrop;
use yii\helpers\Url;

/**
 * @var yii\web\View $this
 * @var app\models\SupplierBarang $model
 * @var app\components\annex\ActiveForm $form
 */

$user = \Yii::$app->user->identity;
$supplier = app\models\Supplier::find();
if ($user !== \app\components\Constant::ROLES['sa']) {
    $supplier->andWhere(['id' => $user->supplier->id]);
}

$supplier = $supplier->all();

$this->registerJsFile(Yii::getAlias("@web/tinymce/tinymce.min.js"));
// $uploadlink = Url::to(['site/upload-image']);
// $csrf = Yii::$app->request->csrfToken;

$this->registerJs("
      tinymce.init({
        selector: '.tinymce-form',
        height: '400',
        plugins: [
            'advlist autolink lists link image charmap print preview anchor',
            'searchreplace visualblocks code fullscreen',
            'insertdatetime media table paste code help wordcount',
        ],

        toolbar: 'undo redo | formatselect | ' +
        'bold italic backcolor | alignleft aligncenter ' +
        'alignright alignjustify | bullist numlist outdent indent | ' +
        'removeformat | help',
      });
");

?>

<?php $form = ActiveForm::begin([
    'id' => 'SupplierBarang',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?=         // modified by Defri Indra
    $form->field($model, 'supplier_id', \app\components\Constant::COLUMN())->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'supplier_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\Supplier::find()->all(), 'id', 'nama_supplier'),
        'options' => [
            'placeholder' => $model->getAttributeLabel('supplier_id'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['supplier_id'])),
        ]
    ]); ?>
    <?= $form->field($model, 'nama_barang', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?=
    // modified by Defri Indra
    $form->field($model, 'material_id', \app\components\Constant::COLUMN())->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'material_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\SupplierMaterial::find()->all(), 'id', 'nama'),
        'options' => [
            'placeholder' => $model->getAttributeLabel('material_id'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['material_id'])),
        ]
    ]); ?>

    <?= yii\helpers\Html::hiddenInput('selected_submaterial', ($model->isNewRecord) ? '' : $model->submaterial_id, ['id' => 'selected_submaterial']) ?>
    <?=         // modified by Defri Indra
    $form->field($model, 'submaterial_id', \app\components\Constant::COLUMN())->widget(\kartik\depdrop\DepDrop::class, [
        'type' => DepDrop::TYPE_SELECT2,
        'options' => ['id' => 'supplierbarang-submaterial_id'],
        'pluginOptions' => [
            'depends' => ['supplierbarang-material_id'],
            'placeholder' => 'Pilih...',
            'url' => yii\helpers\Url::to(['/site/get-sub-material']),
            'initialize' => ($model->isNewRecord) ? false : true,
            'params' => ['selected_submaterial']
        ]
    ]) ?>

    <?=
    // modified by Defri Indra
    $form->field($model, 'satuan_id', \app\components\Constant::COLUMN(2))->widget(\kartik\select2\Select2::classname(), [
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'satuan_id',
        'data' => \yii\helpers\ArrayHelper::map(app\models\MasterSatuan::find()->where(['jenis_satuan_id' => 5])->all(), 'id', 'nama'),
        'options' => [
            'placeholder' => $model->getAttributeLabel('satuan_id'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['satuan_id'])),
        ]
    ]); ?>
    <?= $form->field($model, 'stok', \app\components\Constant::COLUMN(2))->widget(\yii\widgets\MaskedInput::class, [
        'clientOptions' => [
            'alias' =>  'decimal',
            'groupSeparator' => ',',
            'autoGroup' => true
        ],
    ]) ?>
    <?= $form->field($model, 'minimal_beli_satuan', \app\components\Constant::COLUMN())->widget(\yii\widgets\MaskedInput::class, [
        'clientOptions' => [
            'alias' =>  'decimal',
            'groupSeparator' => ',',
            'autoGroup' => true
        ],
    ]) ?>
    <?= $form->field($model, 'minimal_beli_volume', \app\components\Constant::COLUMN())->widget(\yii\widgets\MaskedInput::class, [
        'clientOptions' => [
            'alias' =>  'decimal',
            'groupSeparator' => ',',
            'autoGroup' => true
        ],
    ]) ?>
    <?= $form->field($model, 'harga_ritel', \app\components\Constant::COLUMN())->widget(\yii\widgets\MaskedInput::class, [
        'clientOptions' => [
            'alias' =>  'decimal',
            'groupSeparator' => ',',
            'autoGroup' => true
        ],
    ]) ?>
    <?= $form->field($model, 'harga_proyek', \app\components\Constant::COLUMN())->widget(\yii\widgets\MaskedInput::class, [
        'clientOptions' => [
            'alias' =>  'decimal',
            'groupSeparator' => ',',
            'autoGroup' => true
        ],
    ]) ?>
    <?= $form->field($model, 'deskripsi', \app\components\Constant::COLUMN(1))->textarea(['rows' => 6 ,'class' => 'tinymce-form form-control']) ?>
    <?= fieldUploaImage($model, $form, "gambar") ?>
    <?= $form->field($model, 'status', \app\components\Constant::COLUMN(1))->dropDownList(['1' => 'Aktif', '0' => 'Nonaktif'], ['prompt' => 'Select Option']); ?>

    <div class="clearfix"></div>
    <div id="formparams">
        <?php
        if ($model->isNewRecord == false)
            echo $this->render('_form_param', ['params' => $params, 'model' => $model, 'form' => $form]);
        ?>
    </div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>

<?php

$barang_id = $model->id ? "let barang_id = {$model->id};" : "let barang_id=null;";
$url = Url::to(['get-parameter']);
$js = <<<JS
$('#supplierbarang-material_id').on('change', (event) => {
    $barang_id

    fetch("$url?id=" + event.target.value +"&barang_id="+barang_id).then(res => res.text()).then(res => {
        $("#formparams").html(res);
    });
});
JS;

$this->registerJs($js);
