<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Modal;
use kartik\daterange\DateRangePicker;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\SupplierOrderSearch $searchModel
 */

$this->title = 'Barang Keluar';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <!-- <?= Html::a('<i class="fa fa-print"></i> Export Laporan', ['export'], ['class' => 'btn btn-success']) ?> -->
</p>

<form action="<?= \yii\helpers\Url::to(["/barang-keluar/export"]) ?>" method="GET">
    <div class="col-12 mb-4 pl-0">
        <label for="">Export Laporan</label>
        <table class="table table-borderless table-responsive">
            <tr>
                <td class="pt-0 pl-0">Tanggal Mulai</td>
                <td class="pt-0 pl-0">Tanggal Akhir</td>
                <td class="pt-0 pl-0"></td>
            </tr>
            <tr>
                <td class="pt-0 pl-0">
                    <input type="date" name="start" id="" class="form-control">
                </td>
                <td class="pt-0 pl-0">
                    <input type="date" name="end" id="" class="form-control">
                </td>
                <td class="pt-0 pl-0">
                    <button type="submit" class="btn btn-success">Export</button>
                </td>
            </tr>
        </table>
    </div>
</form>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{pager}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [
                            [
                                'label' => Yii::t('crud', "Filter Tanggal"),
                                'attribute' => 'filterDate',
                                'value' => 'created_at',
                                'format' => 'datetime',
                                'filter' => '<div class="drp-container input-group"><span class="input-group-addon"><i class="fa fa-calendar"></i></span>' .
                                    DateRangePicker::widget([
                                        'model' => $searchModel,
                                        'attribute' => 'filterDate',
                                        'convertFormat' => true,
                                        'pluginOptions' => [
                                            'locale' => [
                                                'format' => 'Y-m-d',
                                                'separator' => ' - ',
                                            ],
                                            'opens' => 'right'
                                        ]
                                    ]) . '</div>',
                                'content' => function ($data) {
                                    return date_format(date_create($data['created_at']), 'Y-m-d');
                                }
                            ],
                            [
                                'attribute' => 'Pembeli',
                                'format' => 'text',
                                'value' => function ($model) {
                                    if ($rel = $model) {
                                        return $rel->supplierOrder->user->name;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            [
                                'attribute' => 'Barang',
                                'format' => 'text',
                                'value' => function ($model) {
                                    if ($rel = $model) {
                                        return $rel->supplierBarang->nama_barang;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            [
                                'attribute' => 'jumlah',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'created_at',
                                'format' => 'iddate',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>