<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Modal;
use yii\widgets\DetailView;
use dmstr\helpers\Html;

?>


<?= DetailView::widget([
    'model' => $model,
    'attributes' => [
        [
            'attribute' => 'Jenis Pembayaran',
            'format' => 'text',
            'value' => function ($model) {
                if ($model->jenis_pembayaran == 1) {
                    return "Cash";
                } elseif ($model->jenis_pembayaran == 2) {
                    return "Termin";
                } else {
                    return "Pembayaran Belum Ditentukan";
                }
            },
        ],
        [
            'attribute' => 'dp_pembayaran',
            'format' => 'text',
            'value' => function ($model) {
                if ($model->dp_pembayaran) {
                    return $model->dp_pembayaran . '%';
                } else {
                    return 'DP Belum Ditentukan Admin';
                }
            },
        ],
        [
            'attribute' => 'nilai_dp',
            'format' => 'html',
            'value' => function ($model) {
                if ($rel = $model->nilai_dp) {
                    return \app\components\Angka::toReadableHarga($rel, false);
                } else {
                    return 'DP Belum Ditentukan Admin';
                }
            },
        ],
        [
            'attribute' => 'bukti_pembayaran',
            'format' => 'html',
            'value' => function ($model) {
                if ($rel = $model->bukti_pembayaran) {
                    return Yii::$app->formatter->asDownload($rel);
                } else {
                    return 'Bukti Pembayaran Belum diunggah';
                }
            },
        ],
        [
            'attribute' => 'keterangan_pembayaran',
            'format' => 'text',
        ],
        [
            'attribute' => 'total_pembayaran',
            'format' => 'html',
            'value' => function ($model) {
                if ($rel = $model->total_pembayaran) {
                    $kurang = $model->nilai_kontrak - $model->total_pembayaran;
                    return \app\components\Angka::toReadableHarga($rel, false) . " (Sisa " . \app\components\Angka::toReadableHarga($kurang, false) . ")";
                } else {
                    return '-';
                }
            },
        ],
        [
            'attribute' => 'status_pembayaran',
            'format' => 'html',
            'value' => function ($model) {
                if ($model->status_pembayaran == 0) {
                    return "Belum Melakukan Pembayaran";
                } elseif ($model->status_pembayaran == 1) {
                    return "Telah Dibayar (Menunggu konfirmasi admin)";
                } elseif ($model->status_pembayaran == 2) {
                    return "Pembayaran Dikonfirmasi";
                } elseif ($model->status_pembayaran == 3) {
                    return "Pembayaran Ditolak (mohon upload bukti pembayaran lagi)";
                }
            },
        ],
        // [
        //     'attribute' => 'alasan_tolak',
        //     'format' => 'html',
        //     'value' => function ($model) {
        //         if ($rel = $model->alasan_tolak) {
        //             return $rel;
        //         } else {
        //             return '-';
        //         }
        //     },
        // ],
    ],
]); ?>

<hr />

<?php
if ($model->status_pembayaran == 0 || $model->status_pembayaran == 3) {
    if ($model->nilai_dp != null) {
        echo Html::a(
            'Upload Bukti Pembayaran DP',
            ['upload-pembayaran-dp', 'id' => $model->kode_unik],
            [
                'class' => 'btn btn-info text-white btn-block',
            ]
        );
    }
} ?>