<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\ProyekTerminSearch $searchModel
 */

$this->title = 'Proyek Termin';
$this->params['breadcrumbs'][] = $this->title;
?>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div>
                    <?= GridView::widget([
                        'layout' => '{summary}{pager}{items}{pager}',
                        'dataProvider' => new \yii\data\ActiveDataProvider([
                            'query' => $model->getProyekTermin(),
                            'pagination' => [
                                'pageSize' => 10,
                                'pageParam' => 'page-proyekTermin',
                            ]
                        ]),
                        'pager'        => [
                            'class'          => app\components\frontend\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'options' => [
                            'class' => 'table-responsive',
                        ],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [
                            [
                                'attribute' => 'termin',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'penyelesaian_pekerjaan',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return $model->penyelesaian_pekerjaan . "%";
                                }
                            ],
                            [
                                'attribute' => 'nilai_pembayaran',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Yii::$app->formatter->asRp($model->nilai_pembayaran);
                                }
                            ],
                            [
                                'attribute' => 'jadwal_pembayaran',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Yii::$app->formatter->asDate($model->jadwal_pembayaran);
                                }
                            ],
                            [
                                'attribute' => 'bukti_pembayaran',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    if ($model->bukti_pembayaran != null) {
                                        return Yii::$app->formatter->asDownload($model->bukti_pembayaran);
                                    } else {
                                        return "-";
                                    }
                                }
                            ],
                            [
                                'attribute' => 'tanggal_pembayaran',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    return Yii::$app->formatter->asDatetime($model->tanggal_pembayaran);
                                }
                            ],
                            [
                                'attribute' => 'status',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    if ($model->status == 0) {
                                        return "Belum Membayar";
                                    } elseif ($model->status == 1) {
                                        return "Sudah Membayar";
                                    }
                                    elseif($model->status == 2)
                                    {
                                        return "Pembayaran Dikonfirmasi";
                                    }
                                    elseif($model->status == 3)
                                    {
                                        return "Pembayaran Ditolak";
                                    }
                                }
                            ],
                            [
                                'attribute' => 'Alasan Tolak Pembayaran',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    if ($model->alasan_tolak_pembayaran != null) {
                                        return $model->alasan_tolak_pembayaran;
                                    } else{
                                        return "-";
                                    }
                                }
                            ],
                            [
                                'attribute' => 'Aksi Pembayaran',
                                'format' => 'raw',
                                'value' => function ($model) {
                                    if ($model->status == 0 || $model->status == 3) {
                                        return Html::a('Bayar Termin', ['bayar-termin', 'id' => $model->kode_unik], ['class' => 'btn btn-primary text-white']);
                                    } elseif ($model->status == 1) {
                                        return "-";
                                    }
                                    elseif($model->status == 2)
                                    {
                                        return "-";
                                    }
                                }
                            ],
                            /*[
            'attribute' => 'created_by',
            'format' => 'text',
        ],*/
                            /*[
            'attribute' => 'updated_by',
            'format' => 'iddate',
        ],*/
                            /*[
            'attribute' => 'created_at',
            'format' => 'iddate',
        ],*/
                            /*[
            'attribute' => 'updated_at',
            'format' => 'iddate',
        ],*/
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>