<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\TentangHomei $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'id' => 'TentangHomei',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?= $form->field($model, 'judul_kiri', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'judul_atas', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'judul_utama', \app\components\Constant::COLUMN(1))->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'isi', \app\components\Constant::COLUMN())->textarea(['rows' => 6]) ?>
    <?= fieldUploaImage($model, $form, 'gambar', ['column' => 2]) ?>
    <?= $this->render("_form_detail", array_merge($model->render(), ['form' => $form])); ?>
    <div class="clearfix"></div>
</div>
<hr />
<div class="row">
    <div class="col-md-12 text-center">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>