<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use dmstr\helpers\Html;
use app\components\annex\Tabs;
use richardfan\widget\JSRegister;

/**
 * @var yii\web\View $this
 * @var app\models\Proyek $model
 */
\app\assets\MapAsset::register($this);
$this->registerCssFile("@web/homepage/css/card.css");

$this->title = 'Manajemen Keuangan';
$this->params['breadcrumbs'][] = ['label' => 'Keuangan', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->nama_proyek, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
$setting = \app\models\SiteSetting::find()->all();
$this->registerCss("

.overlay {
    position:absolute;
    width:100%;
    height:100%;
    background:rgba(0,0,0,0.4);
}
");
?>
<?php \app\components\annex\Modal::begin(['id' => 'modal', 'header' => '<h3 id="modaltitle"></h3>', 'size' => 'modal-lg modal-dialog-centered', 'options' => ['tabindex' => '', 'style' => 'margin-top:10%'], ]) ?>
<div id="modalbody"></div>
<?php \app\components\annex\Modal::end() ?>
<!-- Navigation -->
<section class="navigation">
    <div class="parallax parallax--nav" style="background-image: url(<?= \Yii::$app->request->baseUrl . "/uploads/" . $setting[0]['gambar_header'] ?>);">
        <div class="overlay"></div>
        <div class="container clearfix">
            <div class="row">
                <div class="col-12">
                    <h2>
                        <?= $setting[0]['tagline']; ?>
                    </h2>
                </div>
                <div class="col-12">
                    <p>
                        <?= $setting[0]['tagline2']; ?>
                    </p>
                </div>
                <div class="col-12">
                    <ul class="breadcrumbs ul--inline ul--no-style">
                        <li>
                            <a href="<?= \Yii::$app->request->BaseUrl ?>/home">Home</a>
                        </li>
                        <span>/</span>
                        <li class="active">
                            <a href="<?= \Yii::$app->request->BaseUrl ?>/home/proyek-saya/index">Proyek Saya</a>
                        </li>
                        <span>/</span>
                        <li class="active">
                            <a href="#">Keuangan</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Navigation -->
<!-- Contact content -->
<section class="contact-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title title-3 title--dark">
                    Manajemen Keuangan
                </h2>
            </div>
            <div class="col-lg-3 col-md-3 pb-3">
                <?= $this->render('../_sidemenu', compact('model')) ?>
            </div>
            <div class="col-lg-9 col-md-9">
                <div class="col-lg-12 col-12 layout-spacing">
                    <!-- flash message -->
                    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
                        <span class="alert alert-info alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <?= \Yii::$app->session->getFlash('deleteError') ?>
                        </span>
                    <?php endif; ?>

                    <div class="row">
                        <div class="col-md-6 col-lg-6">
                            <div class="cardx cardx-1 text-center">
                                <div class="cardx__icon">
                                    <span class="font-weight-bold" style="font-size: 1rem;">
                                        Total Anggaran
                                    </span>
                                </div>
                                <p class="cardx__title text-center"><?= Yii::$app->formatter->asRp($total_anggaran) ?></p>
                            </div>
                        </div>
                        <div class="col-md-6 col-lg-6">
                            <div class="cardx cardx-3 text-center">
                                <div class="cardx__icon">
                                    <span class="font-weight-bold" style="font-size: 1rem;">Sisa Anggaran</span>
                                </div>
                                <p class="cardx__title text-center"><?= Yii::$app->formatter->asRp($sisa_anggaran) ?></p>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4">
                            <div class="cardx cardx-4 text-center">
                                <div class="cardx__icon">
                                    <span class="font-weight-bold" style="font-size: 1rem;">Pemasukan</span>
                                </div>
                                <p class="cardx__title text-center"><?= Yii::$app->formatter->asRp($total_pemasukkan) ?></p>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4">
                            <div class="cardx cardx-2 text-center">
                                <div class="cardx__icon">
                                    <span class="font-weight-bold" style="font-size: 1rem;">Pengeluaran</span>
                                </div>
                                <div class="cardx__title text-center">
                                    <div class="row">
                                        <div class="col-12">
                                            <p class=""><?= Yii::$app->formatter->asRp($total_pengeluaran) ?></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4 col-lg-4">
                            <div class="cardx cardx-5 text-center">
                                <div class="cardx__icon">
                                    <span class="font-weight-bold" style="font-size: 1rem;">Total Hutang</span>
                                </div>
                                <div class="cardx__title text-center">
                                    <div class="row">
                                        <div class="col-12">
                                            <p class=""><?= Yii::$app->formatter->asRp($total_hutang) ?></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <?php $this->beginBlock('KeuanganMasuk') ?>
                    <div class="row">
                        <div class="col-md-8">
                            <h4>Keuangan Masuk</h4>
                            <div class="m-b-30">
                                <div class="">
                                    <br>
                                    <?= $this->render('_keuangan_masuk', compact('model')) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <h4>Kategori</h4>
                            <div class="m-b-30">
                                <div class="">
                                    <?= $this->render('_kategori_keuangan_masuk', compact('model')) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php $this->endBlock() ?>

                    <?php $this->beginBlock('KeuanganKeluar') ?>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Keuangan Keluar</h4>
                            <div class="m-b-30">
                                <div class="">
                                    <?= $this->render('_keuangan_keluar', compact('model')) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php $this->endBlock() ?>

                    <?php $this->beginBlock('PurchaseOrder') ?>
                    <div class="row">
                        <div class="col-md-12">
                            <h4>Keuangan Keluar</h4>
                            <div class="m-b-30">
                                <div class="">
                                    <?= $this->render('_keuangan_po', compact('model')) ?>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php $this->endBlock() ?>

                    <?= Tabs::widget(
                        [
                            'id' => 'relation-tabs',
                            'encodeLabels' => false,
                            'linkOptions' => [
                                'class' => 'nav-link mt-5',
                                'style' => '
                            border: groove;
                            border-color: #239ade;
                            border-top: 10px;
                            border-left: 0px;
                            border-right: 0px;
                        ',
                            ],
                            'items' => [
                                [
                                    'label'   => '<b class="">Pemasukkan</b>',
                                    'content' => $this->blocks['KeuanganMasuk'],
                                    'active'  => true,
                                ],
                                [
                                    'label'   => '<b class="">Pengeluaran</b>',
                                    'content' => $this->blocks['KeuanganKeluar'],
                                    'active'  => false,
                                ],
                                [
                                    'label'   => '<b class="">Purchase Order</b>',
                                    'content' => $this->blocks['PurchaseOrder'],
                                    'active'  => false,
                                ],
                            ]
                        ]
                    );
                    ?>

                </div>
            </div>
        </div>
    </div>
</section>

<?php JSRegister::begin() ?>
<script>
    $(function() {

        $('.modalButton').click(function() {
            console.log($(this).attr('value'));
            $('#modal').modal('show')
                .find('#modalContent')
                .load($(this).attr('value'));
        });
    })

    window.openmodal = function(href, title = "Modal") {
        $.ajax(href, {
            success: function(response) {
                $('#modaltitle').html(title);
                $('#modalbody').html(response);
                $('#modal').modal({
                    show: 1
                });
            }
        })
    }
</script>

<?php JSRegister::end() ?>