<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;
use kartik\file\FileInput;

/**
 * @var yii\web\View $this
 * @var app\models\ProyekKemajuanHarian $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'action' => \yii\helpers\Url::current(["id_project" => $proyek_kemajuan->id_proyek]),
    'id' => 'ProyekKemajuanHarian',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?= $form->field($model, 'id_proyek', ['template' => '{input}'])->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'id_proyek_kemajuan', ['template' => '{input}'])->hiddenInput()->label(false); ?>
    <?= $form->field($proyek_kemajuan, 'item', \app\components\Constant::COLUMN(1))->textInput(['readonly' => true]) ?>
    <?= $form->field($proyek_kemajuan, 'volume', \app\components\Constant::COLUMN(3))->textInput(['readonly' => true]) ?>
    <?= $form->field($proyek_kemajuan, 'volume_kemajuan', \app\components\Constant::COLUMN(3))->textInput(['readonly' => true]) ?>
    <?= $form->field($proyek_kemajuan, 'satuan', \app\components\Constant::COLUMN(3))->textInput(['readonly' => true, 'value' => $proyek_kemajuan->satuan->nama]) ?>
    <?= $form->field($model, 'tanggal', \app\components\Constant::COLUMN())->textInput(['type' => 'date', 'value' => date("Y-m-d")]) ?>
    <?= $form->field($model, 'volume', \app\components\Constant::COLUMN())->textInput() ?>
    <?= $form->field($proyek_kemajuan, 'status_verifikasi', \app\components\Constant::COLUMN(1))->dropDownList(
        \app\models\ProyekKemajuan::getStatuses(),
        [
            'prompt' => 'Pilih Status',
        ]
    ) ?>

    <div class="clearfix"></div>
    <hr>
    <div class="clearfix"></div>

    <?= $form->field($modelImage, 'nama_file', \app\components\Constant::COLUMN())->widget(FileInput::class, []) ?>
    <?= $form->field($modelImage, 'keterangan', \app\components\Constant::COLUMN())->textarea(['rows' => 6, 'value' => $proyek_kemajuan->item]) ?>
    <div class="clearfix"></div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['/proyek/view', 'id' => $model->proyekKemajuan->id_proyek], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>