<?php
/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
* @var yii\web\View $this
* @var app\models\search\LogHargaMaterialSearch $model
* @var yii\widgets\ActiveForm $form
*/
?>

<div class="log-harga-material-search">

    <?php $form = ActiveForm::begin([
    'action' => ['index'],
    'method' => 'get',
    ]); ?>

    		<?= $form->field($model, 'id') ?>

		<?= $form->field($model, 'nama_material') ?>

		<?= $form->field($model, 'harga_material') ?>

		<?= $form->field($model, 'provinsi') ?>

		<?= $form->field($model, 'kota') ?>

		<?php // echo $form->field($model, 'nama_supplier') ?>

		<?php // echo $form->field($model, 'created_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
