<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\search\PekerjaanSamedaySearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="pekerjaan-sameday-search">

	<?php $form = ActiveForm::begin([
		'action' => ['index'],
		'method' => 'get',
	]); ?>

	<?= $form->field($model, 'id') ?>

	<?= $form->field($model, 'id_kategori') ?>

	<?= $form->field($model, 'id_pelanggan') ?>

	<?= $form->field($model, 'nama_pelanggan') ?>

	<?= $form->field($model, 'alamat_pelanggan') ?>

	<?php // echo $form->field($model, 'foto_lokasi') 
	?>

	<?php // echo $form->field($model, 'uraian_pekerjaan') 
	?>

	<?php // echo $form->field($model, 'tanggal_survey') 
	?>

	<?php // echo $form->field($model, 'biaya') 
	?>

	<?php // echo $form->field($model, 'layanan_yang_diberikan') 
	?>

	<?php // echo $form->field($model, 'status') 
	?>

	<?php // echo $form->field($model, 'catatan_revisi') 
	?>

	<?php // echo $form->field($model, 'created_at') 
	?>

	<?php // echo $form->field($model, 'updated_at') 
	?>

	<?php // echo $form->field($model, 'flag') 
	?>

	<div class="form-group">
		<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
		<?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
	</div>

	<?php ActiveForm::end(); ?>

</div>