<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\ActiveForm;
use kartik\date\DatePicker;
use kartik\datetime\DateTimePicker;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\PekerjaanSameday $model
 */

$this->title = 'Layanan';
$this->params['breadcrumbs'][] = ['label' => 'Pekerjaan Sameday', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;

$this->registerJsFile(Yii::getAlias("@web/tinymce/tinymce.min.js"));
$this->registerJs("
      tinymce.init({
        selector: '#pekerjaansameday-layanan_yang_diberikan'
      });
");
?>

<div class="row">
    <div class="col-md-12">
        <p>
            <?= Html::a('Kembali', \yii\helpers\Url::previous(), ['class' => 'btn btn-default']) ?>
        </p>
        <div class="card m-b-30">
            <div class="card-body">

                <?php $form = ActiveForm::begin([
                    'id' => 'PekerjaanSameday',
                    'layout' => 'horizontal',
                    'enableClientValidation' => true,
                    'errorSummaryCssClass' => 'error-summary alert alert-error'
                ]);
                ?>
                <?php echo $form->errorSummary($model); ?>

                <div class="clearfix"></div>
                <div class="d-flex  flex-wrap">

                    <?= $form->field($model, 'id_tukang', \app\components\Constant::COLUMN(3))->widget(\kartik\select2\Select2::classname(), [
                        'model' => $model,
                        'data' => \yii\helpers\ArrayHelper::map(app\models\User::find()
                            ->where([
                                'id' => $model->id_tukang,
                                'flag' => 1,
                                'role_id' => \app\components\Constant::ROLE_TUKANG_SAMEDAY,
                            ])->all(), 'id', 'name'),
                        'options' => [
                            'placeholder' => $model->getAttributeLabel('id_tukang'),
                            'multiple' => false,
                        ],
                        "pluginOptions" => [
                            'minimumInputLength' => 3,
                            "allowClear" => true,
                            'language' => [
                                'errorLoading' => new \yii\web\JsExpression("function () { return 'Waiting for results...'; }"),
                            ],
                            'ajax' => [
                                'url' => \yii\helpers\Url::to(['/user/get-user-tukang']),
                                'dataType' => 'json',
                                'data' => new \yii\web\JsExpression('function(params) { 
                                    let id = $("#pekerjaansameday-id_tukang").val();
                                    return {q:params.term, id: id}; 
                                }')
                            ],
                            'escapeMarkup' => new \yii\web\JsExpression('function (markup) { return markup; }'),
                            'templateResult' => new \yii\web\JsExpression('function(city) { return city.text; }'),
                            'templateSelection' => new \yii\web\JsExpression('function (city) { return city.text; }'),
                        ]
                    ]); ?>
                    <?= $form->field($model, 'biaya', \app\components\Constant::COLUMN(3))->widget(\yii\widgets\MaskedInput::class, [
                        'clientOptions' => [
                            'alias' =>  'decimal',
                            'groupSeparator' => ',',
                            'autoGroup' => true
                        ],
                    ]) ?>
                    <?= $form->field($model, 'nominal_dp', \app\components\Constant::COLUMN(3))->widget(\yii\widgets\MaskedInput::class, [
                        'clientOptions' => [
                            'alias' =>  'decimal',
                            'groupSeparator' => ',',
                            'autoGroup' => true
                        ],
                    ]) ?>
                    <?= $form->field($model, 'layanan_yang_diberikan', \app\components\Constant::COLUMN(1))->textarea() ?>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-offset-3 col-md-10">
                        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['view', "id" => $model->id], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>