<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Tabs;
use app\components\Constant;
use dmstr\helpers\Html;
use yii\widgets\DetailView;
use app\models\PekerjaanSameday;

/**
 * @var yii\web\View $this
 * @var app\models\PekerjaanSameday $model
 */


$user = \app\components\Constant::getUser();

$this->title = 'Pekerjaan Sameday : ' . $model->nama_pelanggan;
$this->params['breadcrumbs'][] = ['label' => 'Pekerjaan Sameday', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->nama_pelanggan, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud pekerjaan-sameday-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?php if ($user->role_id == 1 && $model->status != PekerjaanSameday::STATUS_SELESAI) : ?>
            <?= Html::a('<span class="fa fa-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info']) ?>
        <?php endif ?>
        <?php if ($model->status == PekerjaanSameday::STATUS_PELENGKAPAN_DATA) : ?>
            <?= Html::a('<span class="fa fa-pencil"></span> ' . 'Edit Rencana Survey', ['update-rencana-survey', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?php endif ?>
        <?php if ($model->status == PekerjaanSameday::STATUS_SURVEY_LOKASI) : ?>
            <?= Html::a('<span class="fa fa-pencil"></span> ' . 'Penentuan Layanan', ['layanan', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?php endif ?>
        <?php if ($model->status == PekerjaanSameday::STATUS_PEMBAYARAN_DP && $model->catatan_revisi != null) : ?>
            <?= Html::a('<span class="fa fa-pencil"></span> ' . 'Revisi Penentuan Layanan', ['layanan', 'id' => $model->id], ['class' => 'btn btn-warning']) ?>
        <?php endif ?>
        <?php if ($model->status == PekerjaanSameday::STATUS_PEMBAYARAN_DP && $model->revisi_pembayaran_dp == "" && $model->bukti_dp != null) : ?>
            <?= Html::a('<span class="fa fa-check"></span> ' . 'Konfirmasi Pembayaran', ['konfirmasi-dp', 'id' => $model->id], [
                'class' => 'mt-1 mr-1 btn btn-primary',
                "data-confirm" => "Apakah Anda yakin ingin mengonfirmasi data ini ?",
                "data-method" => "POST"
            ]) ?>
            <?= Html::a('<span class="fa fa-times"></span> ' . 'Tolak Pembayaran', ['tolak-dp', 'id' => $model->id], ['class' => 'mt-1 mr-1 btn btn-danger']) ?>
        <?php endif ?>
        <?php if (($model->status == PekerjaanSameday::STATUS_PENGERJAAN || $model->status == PekerjaanSameday::STATUS_DIAJUKAN) && $user->role_id == Constant::ROLE_TUKANG_SAMEDAY) : ?>
            <?= Html::a('<span class="fa fa-check"></span> ' . 'AJUKAN PENGERJAAN', ['pengajuan', 'id' => $model->id], [
                'class' => 'mt-1 mr-1 btn btn-primary',
                "data-confirm" => "Apakah Anda yakin ingin mengonfirmasi data ini ?",
                "data-method" => "POST"
            ]) ?>
        <?php endif ?>
        <?php if ($model->status == PekerjaanSameday::STATUS_PEMBAYARAN && $model->revisi_pembayaran == null) : ?>
            <?= Html::a('<span class="fa fa-check"></span> ' . 'KONFIRMASI PEMBAYARAN AKHIR', ['konfirmasi-pembayaran-total', 'id' => $model->id], [
                'class' => 'mt-1 mr-1 btn btn-primary',
                "data-confirm" => "Apakah Anda yakin ingin mengonfirmasi data ini ?",
                "data-method" => "POST"
            ]) ?>
            <?= Html::a('<span class="fa fa-times"></span> ' . 'REVISI PEMBAYARAN AKHIR', ['revisi-pembayaran-total', 'id' => $model->id], [
                'class' => 'mt-1 mr-1 btn btn-danger',
                "data-confirm" => "Apakah Anda yakin ingin merevisi data ini ?",
                "data-method" => "POST"
            ]) ?>
        <?php endif ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Pekerjaan', ['index'], ['class' => 'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <?php $this->beginBlock('app\models\PekerjaanSameday'); ?>
                    <div class="row">
                        <div class="col-md-4 col-sm-6 col-xs-12">
                            <div class="text-center">
                                <img src="<?= Yii::$app->formatter->asMyImage($model->foto_lokasi, false) ?>" alt="" srcset="" class="img img-fluid">
                            </div>
                        </div>
                        <div class="col-md-8 col-sm-6 col-xs-12">

                            <?= DetailView::widget([
                                'model' => $model,
                                'options' => ['class' => 'table table-borderless table-striped detail-view'],
                                'attributes' => [
                                    [
                                        'attribute' => 'id_kategori',
                                        'format' => 'raw',
                                        'value' => function ($model) {
                                            return $model->getViewKategori();
                                        }
                                    ],
                                    [
                                        'attribute' => 'nama_pelanggan',
                                        'format' => 'text',
                                    ],
                                    [
                                        'attribute' => 'alamat_pelanggan',
                                        'format' => 'ntext',
                                    ],
                                    [
                                        'attribute' => 'uraian_pekerjaan',
                                        'format' => 'html',
                                    ],
                                    [
                                        'attribute' => 'tanggal_survey',
                                        'format' => 'iddate',
                                    ],
                                    [
                                        'attribute' => 'layanan_yang_diberikan',
                                        'format' => 'html',
                                    ],
                                    [
                                        'attribute' => 'id_tukang',
                                        'label' => 'Tukang Yang Mengerjakan',
                                        'filter' => false,
                                        'format' => 'raw',
                                        'value' => function ($model) {
                                            return ($rel = $model->tukang) ? $rel->name : "<label class='p-1 bg-danger text-white' style='border-radius: 5px'>Belum diatur</label>";
                                        }
                                    ],
                                    [
                                        'attribute' => 'catatan_revisi',
                                        'format' => 'html',
                                    ],
                                    [
                                        'attribute' => 'status',
                                        'format' => 'text',
                                        'value' => $model->getStatus()
                                    ],
                                    [
                                        'attribute' => 'created_at',
                                        'format' => 'iddate',
                                    ],
                                    [
                                        'attribute' => 'updated_at',
                                        'format' => 'iddate',
                                    ],
                                ],
                            ]); ?>

                            <hr />

                            <?= Html::a(
                                '<span class="glyphicon glyphicon-trash"></span> ' . 'Delete',
                                ['delete', 'id' => $model->id],
                                [
                                    'class' => 'btn btn-danger',
                                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                                    'data-method' => 'post',
                                ]
                            ); ?>
                        </div>
                    </div>
                    <?php $this->endBlock(); ?>
                    <?php $this->beginBlock('app\models\PekerjaanSameday\Biaya'); ?>
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12">
                            <?= DetailView::widget([
                                'model' => $model,
                                'options' => ['class' => 'table table-borderless table-striped detail-view'],
                                'attributes' => [
                                    [
                                        'attribute' => 'nominal_dp',
                                        'format' => 'rp',
                                    ],
                                    [
                                        'attribute' => 'bukti_dp',
                                        'format' => 'raw',
                                        'value' => function ($model) {
                                            return Yii::$app->formatter->asDownload($model->bukti_dp);
                                        }
                                    ],
                                    [
                                        'attribute' => 'tanggal_pembayaran_dp',
                                        'format' => 'iddate',
                                    ],
                                    [
                                        'attribute' => 'deadline_pembayaran_dp',
                                        'format' => 'iddate',
                                    ],
                                    [
                                        'attribute' => 'keterangan_pembayaran_dp',
                                        'format' => 'html',
                                    ],
                                    [
                                        'attribute' => 'revisi_pembayaran_dp',
                                        'format' => 'html',
                                    ],
                                    [
                                        'attribute' => 'biaya',
                                        'format' => 'rp',
                                    ],
                                    [
                                        'attribute' => 'tanggal_pembayaran',
                                        'format' => 'iddate',
                                    ],
                                    [
                                        'attribute' => 'keterangan_pembayaran',
                                        'format' => 'html',
                                    ],
                                    [
                                        'attribute' => 'bukti_pembayaran',
                                        'format' => 'raw',
                                        'value' => function ($model) {
                                            return Yii::$app->formatter->asDownload($model->bukti_pembayaran);
                                        }
                                    ],
                                ],
                            ]); ?>

                        </div>
                    </div>
                    <?php $this->endBlock(); ?>

                    <?= Tabs::widget([
                        'id' => 'relation-tabs',
                        'encodeLabels' => false,
                        'items' => [
                            [
                                'label' => '<b class=""># Informasi</b>',
                                'content' => $this->blocks['app\models\PekerjaanSameday'],
                                'active' => true,
                            ],
                            [
                                'content' => $this->blocks['app\models\PekerjaanSameday\Biaya'],
                                'label' => '<small>Biaya</small>',
                                'active' => false,
                            ],
                        ],
                    ]) ?>
                </div>
            </div>
        </div>
    </div>
</div>