<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\ActiveForm;
use yii\helpers\Html;

use \app\components\annex\Tabs;
use kartik\depdrop\DepDrop;

/**
 * @var yii\web\View $this
 * @var app\models\IsianLanjutan $model
 * @var app\components\annex\ActiveForm $form
 */

?>
<?php
$setting = \app\models\SiteSetting::find()->all();
$this->registerCss("

.overlay {
    position:absolute;
    width:100%;
    height:100%;
    background:rgba(0,0,0,0.4);
}
");
?>
<!-- Navigation -->
<section class="navigation">
    <div class="parallax parallax--nav" style="background-image: url(<?= \Yii::$app->request->baseUrl . "/uploads/" . $setting[0]['gambar_header'] ?>);">
        <div class="overlay"></div>
        <div class="container clearfix">
            <div class="row">
                <div class="col-12">
                    <h2>
                        <?= $setting[0]['tagline']; ?>
                    </h2>
                </div>
                <div class="col-12">
                    <p>
                        <?= $setting[0]['tagline2']; ?>
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Navigation -->
<!-- Contact content -->
<section class="contact-content">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="m-t-40">
                    <img src="<?= \Yii::$app->request->baseUrl . "/homepage/img/offers.jpg" ?>" alt="">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-contact-wrap m-t-40">
                    <h4>Deal Project</h4>
                    <!-- display success message -->
                    <?php if (Yii::$app->session->hasFlash('success')) : ?>
                        <div class="alert alert-success alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <p><i class="icon fa fa-check"></i>Saved!</p>
                            <?= Yii::$app->session->getFlash('success') ?>
                        </div>
                    <?php endif; ?>

                    <!-- display error message -->
                    <?php if (Yii::$app->session->hasFlash('error')) : ?>
                        <div class="alert alert-danger alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            <h4><i class="icon fa fa-check"></i>Saved!</h4>
                            <?= Yii::$app->session->getFlash('error') ?>
                        </div>
                    <?php endif; ?>
                    <?php $form = ActiveForm::begin([
                        'id' => 'DealPelanggan',
                        'layout' => 'horizontal',
                        'enableClientValidation' => true,
                        'errorSummaryCssClass' => 'error-summary alert alert-error'
                    ]);
                    ?>
                    <?php echo $form->errorSummary($model); ?>

                    <div class="row">
                        <div class="col-md-12 col-12">
                            <?php
                            $penawaran = app\models\Penawaran::find()->where(['id' => $_GET['id']])->one();
                            echo $form->field($model, 'id_penawaran', [
                                'template' => '
                                        {label}
                                        {input}
                                        {error}
                                    ',
                                'inputOptions' => [
                                    'class' => 'form-control'
                                ],
                                'labelOptions' => [
                                    'class' => 'control-label'
                                ],
                                'options' => ['tag' => false]
                            ])->textInput(['disabled' => true, 'value' => $penawaran->kode_penawaran]);
                            ?>

                            <?=         // modified by Defri Indra
                            $form->field($model, 'id_kontraktor', [
                                'template' => '
                                        {label}
                                        {input}
                                        {error}
                                    ',
                                'inputOptions' => [
                                    'class' => ''
                                ],
                                'labelOptions' => [
                                    'class' => 'control-label'
                                ],
                            ])->widget(\kartik\select2\Select2::classname(), [
                                'name' => 'class_name',
                                'model' => $model,
                                'attribute' => 'id_kontraktor',
                                'data' => \yii\helpers\ArrayHelper::map(app\models\Kontraktor::find()->all(), 'id', 'nama_kontraktor'),
                                'options' => [
                                    'placeholder' => $model->getAttributeLabel('id_kontraktor'),
                                    'multiple' => false,
                                    'disabled' => (isset($relAttributes) && isset($relAttributes['id_kontraktor'])),
                                ]
                            ]); ?>
                            <?= $form->field($model, 'nama_pelanggan', [
                                'template' => '
                                        {label}
                                        {input}
                                        {error}
                                    ',
                                'inputOptions' => [
                                    'class' => 'form-control'
                                ],
                                'labelOptions' => [
                                    'class' => 'control-label'
                                ],
                            ])->textInput(['maxlength' => true]) ?>
                            <?= $form->field($model, 'no_hp', [
                                'template' => '
                                        {label}
                                        {input}
                                        {error}
                                    ',
                                'inputOptions' => [
                                    'class' => 'form-control'
                                ],
                                'labelOptions' => [
                                    'class' => 'control-label'
                                ],
                            ])->textInput(['maxlength' => true]) ?>
                            <?= $form->field($model, 'alamat_pelanggan', [
                                'template' => '
                                        {label}
                                        {input}
                                        {error}
                                    ',
                                'inputOptions' => [
                                    'class' => 'form-control'
                                ],
                                'labelOptions' => [
                                    'class' => 'control-label'
                                ],
                            ])->textInput(['maxlength' => true]) ?>
                            <?= $form->field($model, 'alamat_proyek', [
                                'template' => '
                                        {label}
                                        {input}
                                        {error}
                                    ',
                                'inputOptions' => [
                                    'class' => 'form-control'
                                ],
                                'labelOptions' => [
                                    'class' => 'control-label'
                                ],
                            ])->textInput(['maxlength' => true]) ?>
                        </div>
                    </div>

                    <div class="clearfix"></div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-offset-3 col-md-10">
                        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</section>
<!-- End Contact Content -->

<?php
$this->registerJsFile("@web/homepage/vendor/jquery-3.2.1.min.js", ['position' => \yii\web\View::POS_END]);
?>