<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;
use kartik\file\FileInput;
use yii\helpers\Url;

$setting = \app\models\SiteSetting::find()->one();
/**
 * @var yii\web\View $this
 * @var app\models\ProyekKemajuan $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<div class="row">
    <div class="col-md-12">
        <p>
            <?= Html::a('Kembali', \yii\helpers\Url::previous(), ['class' => 'btn btn-default']) ?>
        </p>
        <div class="card m-b-30">
            <div class="card-body">
                <?php $form = ActiveForm::begin([
                    'id' => 'ProyekKemajuan',
                    'layout' => 'horizontal',
                    'enableClientValidation' => true,
                    'errorSummaryCssClass' => 'error-summary alert alert-error'
                ]);
                ?>
                <?php echo $form->errorSummary($model); ?>

                <div class="clearfix"></div>
                <div class="d-flex  flex-wrap">
                    <div class="col-md-12 text-center">
                        <a href="<?= Yii::getAlias("@file/$setting->contoh_import_excel") ?>" class='btn btn-primary text-white' target='_blank'>Download Template Import Excel</a>
                    </div>
                    <?= $form->field($model, 'excel', \app\components\Constant::COLUMN(1))->widget(FileInput::class, [
                        'options' => ['accept' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel'],
                        'pluginOptions' => [
                            'allowedFileExtensions' => ['xlsx', 'xls'],
                            // 'maxFileSize' => 6500,
                            'dropZoneEnabled' => true,
                            'showCaption' => true,
                            'showRemove' => true,
                            'showUpload' => true,
                            'browseLabel' => 'Upload File',
                        ],
                    ]) ?>
                    <div class="clearfix"></div>
                </div>
                <hr />
                <div class="row">
                    <div class="col-md-12 text-center">
                        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['/proyek/view', 'id' => $_GET['id']], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
                <?php ActiveForm::end(); ?>
            </div>
        </div>
    </div>
</div>