<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\annex\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\ProyekKeuanganKeluar $model
 */

$this->title = 'Proyek Keuangan Keluar : ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Proyek Keuangan Keluar', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud proyek-keuangan-keluar-view">
    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <?php $this->beginBlock('app\models\ProyekKeuanganKeluar'); ?>

                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            // modified by Defri Indra
                            [
                                'format' => 'html',
                                'attribute' => 'id_proyek',
                                'value' => ($model->proyek ? $model->proyek->id : '<span class="label label-warning">?</span>'),
                            ],
                            [
                                'attribute' => 'no_po',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'dokumen_po',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'no_invoice',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'keterangan',
                                'format' => 'ntext',
                            ],
                            [
                                'attribute' => 'tanggal',
                                'format' => 'iddate',
                            ],
                            [
                                'attribute' => 'total_jumlah',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'vendor',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'tipe',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'status',
                                'format' => 'text',
                                'value' => function ($model) {
                                    return $model->getStatus();
                                }
                            ],
                            // [
                            //     'attribute' => 'created_at',
                            //     'format' => 'iddate',
                            // ],
                            // // modified by Defri Indra
                            // [
                            //     'format' => 'html',
                            //     'attribute' => 'created_by',
                            //     'value' => ($model->createdBy ? $model->createdBy->name : '<span class="label label-warning">?</span>'),
                            // ],
                            // [
                            //     'attribute' => 'updated_at',
                            //     'format' => 'iddate',
                            // ],
                            // // modified by Defri Indra
                            // [
                            //     'format' => 'html',
                            //     'attribute' => 'updated_by',
                            //     'value' => ($model->updatedBy ? $model->updatedBy->name : '<span class="label label-warning">?</span>'),
                            // ],
                            // [
                            //     'attribute' => 'deleted_at',
                            //     'format' => 'iddate',
                            // ],
                            // // modified by Defri Indra
                            // [
                            //     'format' => 'html',
                            //     'attribute' => 'deleted_by',
                            //     'value' => ($model->deletedBy ? $model->deletedBy->name : '<span class="label label-warning">?</span>'),
                            // ],
                        ],
                    ]); ?>

                    <hr />

                    <?= Html::a(
                        '<span class="glyphicon glyphicon-trash"></span> ' . 'Delete',
                        ['delete', 'id' => $model->id],
                        [
                            'class' => 'btn btn-danger',
                            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                            'data-method' => 'post',
                        ]
                    ); ?>
                    <?php $this->endBlock(); ?>



                    <?php $this->beginBlock('ProyekKeuanganKeluarBayars'); ?>
                    <div style='position: relative'>
                        <div style='position:absolute; right: 0px; top: 0px;'>
                            <?= Html::a(
                                '<span class="glyphicon glyphicon-list"></span> ' . 'Semua Data' . ' Proyek Keuangan Keluar Bayars',
                                ['proyek-keuangan-keluar-bayar/index'],
                                ['class' => 'btn text-muted btn-xs']
                            ) ?>
                            <?= Html::a(
                                '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Proyek Keuangan Keluar Bayar',
                                ['proyek-keuangan-keluar-bayar/create', 'ProyekKeuanganKeluarBayar' => ['Array' => $model->id]],
                                ['class' => 'btn btn-success btn-xs']
                            ); ?>
                        </div>
                    </div><?php Pjax::begin(['id' => 'pjax-ProyekKeuanganKeluarBayars', 'enableReplaceState' => false, 'linkSelector' => '#pjax-ProyekKeuanganKeluarBayars ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("defrindr")}']]) ?>
                    <?= '<div class="table-responsive">'
                        .                     \yii\grid\GridView::widget([
                            'layout' => '{summary}{pager}<br/>{items}{pager}',
                            'dataProvider' => new \yii\data\ActiveDataProvider([
                                'query' => $model->getProyekKeuanganKeluarBayars(),
                                'pagination' => [
                                    'pageSize' => 20,
                                    'pageParam' => 'page-proyekkeuangankeluarbayars',
                                ]
                            ]),
                            'pager'        => [
                                'class'          => \app\components\annex\LinkPager::className(),
                                'firstPageLabel' => 'First',
                                'lastPageLabel'  => 'Last'
                            ],
                            'columns' => [
                                [
                                    'class'      => 'yii\grid\ActionColumn',
                                    'template'   => '{view} {update}',
                                    'contentOptions' => ['nowrap' => 'nowrap'],
                                    'urlCreator' => function ($action, $model, $key, $index) {
                                        // using the column name as key, not mapping to 'id' like the standard generator
                                        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                                        $params[0] = 'proyek-keuangan-keluar-bayar' . '/' . $action;
                                        $params['ProyekKeuanganKeluarBayar'] = ['id_keuangan_keluar' => $model->primaryKey()[0]];
                                        return $params;
                                    },
                                    'buttons'    => [],
                                    'controller' => 'proyek-keuangan-keluar-bayar'
                                ],
                                // modified by Defri Indra
                                [
                                    'class' => yii\grid\DataColumn::className(),
                                    'attribute' => 'id_proyek',
                                    'value' => function ($model) {
                                        if ($rel = $model->proyek) {
                                            return $rel->id;
                                        } else {
                                            return '';
                                        }
                                    },
                                    'format' => 'raw',
                                ],
                                [
                                    'attribute' => 'tanggal',
                                    'format' => 'iddate',
                                ],
                                [
                                    'attribute' => 'dibayar',
                                    'format' => 'text',
                                ],
                                [
                                    'attribute' => 'created_at',
                                    'format' => 'iddate',
                                ],
                                [
                                    'attribute' => 'updated_at',
                                    'format' => 'iddate',
                                ],
                                [
                                    'attribute' => 'deleted_at',
                                    'format' => 'iddate',
                                ],
                                // modified by Defri Indra
                                [
                                    'class' => yii\grid\DataColumn::className(),
                                    'attribute' => 'created_by',
                                    'value' => function ($model) {
                                        if ($rel = $model->createdBy) {
                                            return $rel->name;
                                        } else {
                                            return '';
                                        }
                                    },
                                    'format' => 'raw',
                                ],
                                // modified by Defri Indra
                                [
                                    'class' => yii\grid\DataColumn::className(),
                                    'attribute' => 'updated_by',
                                    'value' => function ($model) {
                                        if ($rel = $model->updatedBy) {
                                            return $rel->name;
                                        } else {
                                            return '';
                                        }
                                    },
                                    'format' => 'raw',
                                ],
                                // modified by Defri Indra
                                [
                                    'class' => yii\grid\DataColumn::className(),
                                    'attribute' => 'deleted_by',
                                    'value' => function ($model) {
                                        if ($rel = $model->deletedBy) {
                                            return $rel->name;
                                        } else {
                                            return '';
                                        }
                                    },
                                    'format' => 'raw',
                                ],
                            ]
                        ])
                        . '</div>' ?>
                    <?php Pjax::end() ?>
                    <?php $this->endBlock() ?>


                    <?= Tabs::widget(
                        [
                            'id' => 'relation-tabs',
                            'encodeLabels' => false,
                            'items' => [
                                [
                                    'label'   => '<b class=""># ' . $model->id . '</b>',
                                    'content' => $this->blocks['app\models\ProyekKeuanganKeluar'],
                                    'active'  => true,
                                ],                        [
                                    'content' => $this->blocks['ProyekKeuanganKeluarBayars'],
                                    'label'   => '<small>Proyek Keuangan Keluar Bayars <span class="badge badge-default">' . count($model->getProyekKeuanganKeluarBayars()->asArray()->all()) . '</span></small>',
                                    'active'  => false,
                                ],
                            ]
                        ]
                    );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>