<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;

/**
 * @var yii\web\View $this
 * @var app\models\ProyekKeuanganKeluarDetail $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'action' => \yii\helpers\Url::current(["id_project" => $model->id_proyek]),
    'id' => 'ProyekKeuanganKeluarDetail',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?= $form->field($model, 'item', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'satuan', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?= $form->field($model, 'kuantitas', \app\components\Constant::COLUMN())->textInput() ?>
    <?= $form->field($model, 'harga_satuan', \app\components\Constant::COLUMN())->textInput() ?>
    <?= $form->field($model, 'jumlah', \app\components\Constant::COLUMN())->textInput() ?>
    <?= $form->field($model, 'deskripsi', \app\components\Constant::COLUMN())->textarea(['rows' => 6]) ?>
    <div class="clearfix"></div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>