<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;
use yii\behaviors\BlameableBehavior;
use yii\behaviors\TimestampBehavior;

/**
 * This is the base-model class for table "t_isian_lanjutan".
 *
 * @property integer $id
 * @property string $kode_unik
 * @property string $kode_proyek
 * @property integer $id_satuan
 * @property integer $id_konsep_design
 * @property integer $id_penawaran
 * @property integer $id_user
 * @property integer $id_kontraktor
 * @property integer $id_proyek
 * @property integer $id_lantai
 * @property string $id_wilayah_provinsi
 * @property string $id_wilayah_kota
 * @property string $id_wilayah_kecamatan
 * @property string $id_wilayah_desa
 * @property string $alamat_pelanggan
 * @property string $alamat_proyek
 * @property string $latitude
 * @property string $longitude
 * @property string $nama_awal
 * @property string $nama_akhir
 * @property string $no_hp
 * @property string $label
 * @property string $panjang
 * @property string $lebar
 * @property string $budget
 * @property string $luas_tanah
 * @property string $rencana_pembangunan
 * @property string $rencana_survey
 * @property string $keterangan
 * @property string $dokumen_tor
 * @property integer $approval_dokumen_tor
 * @property integer $dp_pembayaran
 * @property string $bukti_pembayaran
 * @property string $tanggal_pembayaran
 * @property string $keterangan_pembayaran
 * @property integer $status_pembayaran
 * @property string $alasan_tolak
 * @property string $alasan_tolak_tor
 * @property string $boq_proyek
 * @property string $nomor_spk
 * @property string $informasi_proyek
 * @property integer $status_boq
 * @property string $created_at
 * @property string $updated_at
 * @property string $deleted_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $deleted_by
 * @property integer $is_beli_material
 * @property integer $flag
 * @property integer $status
 *
 * @property \app\models\DealPelanggan[] $dealPelanggans
 * @property \app\models\MasterKonsepDesain $konsepDesign
 * @property \app\models\User $user
 * @property \app\models\MasterLantai $lantai
 * @property \app\models\WilayahProvinsi $wilayahProvinsi
 * @property \app\models\WilayahKota $wilayahKota
 * @property \app\models\WilayahKecamatan $wilayahKecamatan
 * @property \app\models\WilayahDesa $wilayahDesa
 * @property \app\models\Kontraktor $kontraktor
 * @property \app\models\MasterSatuan $satuan
 * @property \app\models\User $createdBy
 * @property \app\models\User $updatedBy
 * @property \app\models\User $deletedBy
 * @property \app\models\Penawaran $penawaran
 * @property \app\models\IsianLanjutanRuangan[] $isianLanjutanRuangans
 * @property \app\models\IsianLanjutanRuangan[] $isianLanjutanRuangans0
 * @property \app\models\MasterMenu[] $masterMenus
 * @property \app\models\SupplierOrder[] $supplierOrders
 * @property string $aliasModel
 */
abstract class IsianLanjutan extends \yii\db\ActiveRecord
{


    public $list_ruangan;
    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    const SCENARIO_DELETE = 'delete';
    const SCENARIO_INITIAL_CREATE = 'init-create';
    const SCENARIO_SURVEY = "survey-lokasi";
    const SCENARIO_DP = "dp";
    const SCENARIO_BAYARDP = 'bayardp';
    const SCENARIO_BAYAR_TERMIN = 'bayarcicilan';
    const SCENARIO_KONFIRMASI = 'konfirmasi';
    const SCENARIO_BAYARDPULANG = 'bayardpulang';
    const SCENARIO_BANGUN = "scenario-bangun";
    const SCENARIO_DEAL = "scenario-deal";
    const SCENARIO_TOLAK = "scenario-tolak";
    const SCENARIO_TOLAK_DP = "scenario-tolak-dp";
    const SCENARIO_UPLOAD_TOR = 'upload-tor';
    const SCENARIO_APPROVE_TOR = 'approve-tor';
    const SCENARIO_BATAL_PROYEK = 'batal-proyek';
    const SCENARIO_REVISI_RENCANA_PEMBANGUNAN = 'revisi-rencana-pembangunan';
    const SCENARIO_DEAL_RENCANA_PEMBANGUNAN = "scenario-deal-rencana-pembangunan";
    const SCENARIO_STATUS_BOQ = 'status-boq';
    public $_render = [];

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();
        $parent = parent::fields();

        if (isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function ($model) {
                return $model->id;
            };
        endif;
        if (isset($parent['kode_unik'])) :
            unset($parent['kode_unik']);
            $parent['kode_unik'] = function ($model) {
                return $model->kode_unik;
            };
        endif;
        if (isset($parent['kode_proyek'])) :
            unset($parent['kode_proyek']);
            $parent['kode_proyek'] = function ($model) {
                return $model->kode_proyek;
            };
        endif;
        if (isset($parent['id_satuan'])) :
            unset($parent['id_satuan']);
            $parent['id_satuan'] = function ($model) {
                return $model->id_satuan;
            };
            $parent['_satuan'] = function ($model) {
                $rel = $model->getSatuan()->select([
                    'nama',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_konsep_design'])) :
            unset($parent['id_konsep_design']);
            $parent['id_konsep_design'] = function ($model) {
                return $model->id_konsep_design;
            };
            $parent['_konsep_design'] = function ($model) {
                $rel = $model->getKonsepDesign()->select([
                    'nama_konsep',
                    'gambar'
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_penawaran'])) :
            unset($parent['id_penawaran']);
            $parent['id_penawaran'] = function ($model) {
                return $model->id_penawaran;
            };
            $parent['_penawaran'] = function ($model) {
                $rel = $model->getPenawaran()->select([
                    'id',
                    "kode_unik",
                    "kode_penawaran",
                    "tgl_transaksi",
                    "estimasi_waktu",
                    "harga_penawaran",
                    "total_harga_penawaran",
                    "created_at",
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_user'])) :
            unset($parent['id_user']);
            $parent['id_user'] = function ($model) {
                return $model->id_user;
            };
            $parent['_user'] = function ($model) {
                $rel = $model->getUser()->select([
                    'username',
                    'name',
                    'photo_url',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_kontraktor'])) :
            unset($parent['id_kontraktor']);
            $parent['id_kontraktor'] = function ($model) {
                return $model->id_kontraktor;
            };
            $parent['_kontraktor'] = function ($model) {
                $rel = $model->getKontraktors()->select([
                    'nama_kontraktor',
                    'alamat',
                    'telepon',
                    'created_at',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_proyek'])) :
            unset($parent['id_proyek']);
            $parent['id_proyek'] = function ($model) {
                return $model->id_proyek;
            };
        endif;
        if (isset($parent['id_lantai'])) :
            unset($parent['id_lantai']);
            $parent['id_lantai'] = function ($model) {
                return $model->id_lantai;
            };
            $parent['_lantai'] = function ($model) {
                $rel = $model->getLantai()->select([
                    'nama',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_wilayah_provinsi'])) :
            unset($parent['id_wilayah_provinsi']);
            $parent['id_wilayah_provinsi'] = function ($model) {
                return $model->id_wilayah_provinsi;
            };
            $parent['_wilayah_provinsi'] = function ($model) {
                $rel = $model->getWilayahProvinsi()->select([
                    'nama',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_wilayah_kota'])) :
            unset($parent['id_wilayah_kota']);
            $parent['id_wilayah_kota'] = function ($model) {
                return $model->id_wilayah_kota;
            };
            $parent['_wilayah_kota'] = function ($model) {
                $rel = $model->getWilayahKota()->select([
                    'nama',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_wilayah_kecamatan'])) :
            unset($parent['id_wilayah_kecamatan']);
            $parent['id_wilayah_kecamatan'] = function ($model) {
                return $model->id_wilayah_kecamatan;
            };
            $parent['_wilayah_kecamatan'] = function ($model) {
                $rel = $model->getWilayahKecamatan()->select([
                    'nama',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_wilayah_desa'])) :
            unset($parent['id_wilayah_desa']);
            $parent['id_wilayah_desa'] = function ($model) {
                return $model->id_wilayah_desa;
            };
            $parent['_wilayah_desa'] = function ($model) {
                $rel = $model->getWilayahDesa()->select([
                    'nama',
                ])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['alamat_pelanggan'])) :
            unset($parent['alamat_pelanggan']);
            $parent['alamat_pelanggan'] = function ($model) {
                return $model->alamat_pelanggan;
            };
        endif;
        if (isset($parent['alamat_proyek'])) :
            unset($parent['alamat_proyek']);
            $parent['alamat_proyek'] = function ($model) {
                return $model->alamat_proyek;
            };
        endif;
        if (isset($parent['latitude'])) :
            unset($parent['latitude']);
            $parent['latitude'] = function ($model) {
                return $model->latitude;
            };
        endif;
        if (isset($parent['longitude'])) :
            unset($parent['longitude']);
            $parent['longitude'] = function ($model) {
                return $model->longitude;
            };
        endif;
        if (isset($parent['nama_awal'])) :
            unset($parent['nama_awal']);
            $parent['nama_awal'] = function ($model) {
                return $model->nama_awal;
            };
        endif;
        if (isset($parent['nama_akhir'])) :
            unset($parent['nama_akhir']);
            $parent['nama_akhir'] = function ($model) {
                return $model->nama_akhir;
            };
        endif;
        if (isset($parent['no_hp'])) :
            unset($parent['no_hp']);
            $parent['no_hp'] = function ($model) {
                return $model->no_hp;
            };
        endif;
        if (isset($parent['label'])) :
            unset($parent['label']);
            $parent['label'] = function ($model) {
                return $model->label;
            };
        endif;
        if (isset($parent['panjang'])) :
            unset($parent['panjang']);
            $parent['panjang'] = function ($model) {
                return $model->panjang;
            };
        endif;
        if (isset($parent['lebar'])) :
            unset($parent['lebar']);
            $parent['lebar'] = function ($model) {
                return $model->lebar;
            };
        endif;
        if (isset($parent['budget'])) :
            unset($parent['budget']);
            $parent['budget'] = function ($model) {
                return $model->budget;
            };
        endif;
        if (isset($parent['luas_tanah'])) :
            unset($parent['luas_tanah']);
            $parent['luas_tanah'] = function ($model) {
                return $model->luas_tanah;
            };
        endif;
        if (isset($parent['rencana_pembangunan'])) :
            unset($parent['rencana_pembangunan']);
            $parent['rencana_pembangunan'] = function ($model) {
                return \Yii::$app->formatter->asIddate($model->rencana_pembangunan, false);
            };
        endif;
        if (isset($parent['rencana_survey'])) :
            unset($parent['rencana_survey']);
            $parent['rencana_survey'] = function ($model) {
                return \Yii::$app->formatter->asIddate($model->rencana_survey, false);
            };
        endif;
        if (isset($parent['keterangan'])) :
            unset($parent['keterangan']);
            $parent['keterangan'] = function ($model) {
                return $model->keterangan;
            };
        endif;
        if (isset($parent['dokumen_tor'])) :
            unset($parent['dokumen_tor']);
            $parent['dokumen_tor'] = function ($model) {
                return \Yii::$app->formatter->asFileLink($model->dokumen_tor);
            };
        endif;
        if (isset($parent['approval_dokumen_tor'])) :
            unset($parent['approval_dokumen_tor']);
            $parent['approval_dokumen_tor'] = function ($model) {
                return $model->approval_dokumen_tor;
            };
        endif;
        if (isset($parent['dp_pembayaran'])) :
            unset($parent['dp_pembayaran']);
            $parent['dp_pembayaran'] = function ($model) {
                return $model->dp_pembayaran;
            };
        endif;
        if (isset($parent['bukti_pembayaran'])) :
            unset($parent['bukti_pembayaran']);
            $parent['bukti_pembayaran'] = function ($model) {
                return Yii::$app->formatter->asFileLink($model->bukti_pembayaran);
            };
        endif;
        if (isset($parent['tanggal_pembayaran'])) :
            unset($parent['tanggal_pembayaran']);
            $parent['tanggal_pembayaran'] = function ($model) {
                return \app\components\Tanggal::toReadableDate($model->tanggal_pembayaran, false);
            };
        endif;
        if (isset($parent['keterangan_pembayaran'])) :
            unset($parent['keterangan_pembayaran']);
            $parent['keterangan_pembayaran'] = function ($model) {
                return $model->keterangan_pembayaran;
            };
        endif;
        if (isset($parent['status_pembayaran'])) :
            unset($parent['status_pembayaran']);
            $parent['status_pembayaran'] = function ($model) {
                return $model->status_pembayaran;
            };
        endif;
        if (isset($parent['alasan_tolak'])) :
            unset($parent['alasan_tolak']);
            $parent['alasan_tolak'] = function ($model) {
                return $model->alasan_tolak;
            };
        endif;
        if (isset($parent['alasan_tolak_tor'])) :
            unset($parent['alasan_tolak_tor']);
            $parent['alasan_tolak_tor'] = function ($model) {
                return $model->alasan_tolak_tor;
            };
        endif;
        if (isset($parent['boq_proyek'])) :
            unset($parent['boq_proyek']);
            $parent['boq_proyek'] = function ($model) {
                return Yii::$app->formatter->asFileLink($model->boq_proyek);
            };
        endif;
        if (isset($parent['nomor_spk'])) :
            unset($parent['nomor_spk']);
            $parent['nomor_spk'] = function ($model) {
                return $model->nomor_spk;
            };
        endif;
        if (isset($parent['informasi_proyek'])) :
            unset($parent['informasi_proyek']);
            $parent['informasi_proyek'] = function ($model) {
                return $model->informasi_proyek;
            };
        endif;
        if (isset($parent['status_boq'])) :
            unset($parent['status_boq']);
            $parent['status_boq'] = function ($model) {
                return $model->status_boq;
            };
        endif;
        if (isset($parent['created_at'])) :
            unset($parent['created_at']);
            $parent['created_at'] = function ($model) {
                return \app\components\Tanggal::toReadableDate($model->created_at, false);
            };
        endif;
        if (isset($parent['updated_at'])) :
            unset($parent['updated_at']);
            $parent['updated_at'] = function ($model) {
                return \app\components\Tanggal::toReadableDate($model->updated_at, false);
            };
        endif;
        if (isset($parent['deleted_at'])) :
            unset($parent['deleted_at']);
            $parent['deleted_at'] = function ($model) {
                return \Yii::$app->formatter->asIddate($model->deleted_at, false);
            };
        endif;
        if (isset($parent['created_by'])) :
            unset($parent['created_by']);
            $parent['created_by'] = function ($model) {
                return $model->created_by;
            };
            $parent['_created_by'] = function ($model) {
                $rel = $model->getCreatedBy()->select(['username', 'name'])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['updated_by'])) :
            unset($parent['updated_by']);
            $parent['updated_by'] = function ($model) {
                return $model->updated_by;
            };
            $parent['_updated_by'] = function ($model) {
                $rel = $model->getUpdatedBy()->select(['username', 'name'])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['deleted_by'])) :
            unset($parent['deleted_by']);
            $parent['deleted_by'] = function ($model) {
                return $model->deleted_by;
            };
            $parent['_deleted_by'] = function ($model) {
                $rel = $model->getDeletedBy()->select(['username', 'name'])->one();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['is_beli_material'])) :
            unset($parent['is_beli_material']);
            $parent['is_beli_material'] = function ($model) {
                return $model->is_beli_material;
            };
        endif;
        if (isset($parent['flag'])) :
            unset($parent['flag']);
        endif;
        if (isset($parent['status'])) :
            unset($parent['status']);
            $parent['status'] = function ($model) {
                return $model->status;
            };
            $parent['_status'] = function ($model) {
                return $model::getStatuses()[$model->status];
            };
        endif;


        // $parent['deal_pelanggan'] = function($model) {
        //     $rel = $model->dealPelanggans;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };
        // $parent['hasil_konsultasi'] = function($model) {
        //     $rel = $model->hasilKonsultasis;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };
        // $parent['isian_lanjutan_ruangan'] = function($model) {
        //     $rel = $model->isianLanjutanRuangans;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };
        // $parent['isian_lanjutan_ruangans'] = function($model) {
        //     $rel = $model->isianLanjutanRuangans0;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };
        // $parent['konsultasi'] = function($model) {
        //     $rel = $model->konsultasis;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };
        // $parent['master_menu'] = function($model) {
        //     $rel = $model->masterMenus;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };

        // if request route contain view
        if (\app\components\Constant::isUriContain(['view'])) {
            $parent['penawaran'] = function ($model) {
                $rel = $model->getPenawarans()->select([
                    'id',
                    "kode_unik",
                    "kode_isian_lanjutan",
                    "kode_penawaran",
                    "tgl_transaksi",
                    "estimasi_waktu",
                    "harga_penawaran",
                    "total_harga_penawaran",
                    "created_at",
                ])->all();
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        }


        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_isian_lanjutan';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class' => BlameableBehavior::className(),
            ],
            [
                'class' => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value' => date("Y-m-d H:i:s"),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kode_unik', 'id_satuan', 'id_konsep_design', 'id_lantai', 'id_wilayah_provinsi', 'id_wilayah_kota', 'id_wilayah_kecamatan', 'id_wilayah_desa', 'nama_awal', 'nama_akhir', 'no_hp', 'panjang', 'lebar', 'budget', 'luas_tanah', 'rencana_pembangunan', 'rencana_survey', 'latitude', 'longitude'], 'required'],
            // [['id_user'], 'required'],
            [['id_satuan', 'id_konsep_design', 'id_penawaran', 'id_kontraktor', 'id_user', 'id_lantai', 'created_by', 'updated_by', 'deleted_by', 'flag', 'status', 'id_proyek', 'nilai_dp', 'status_pembayaran', 'is_beli_material', 'status_boq'], 'integer'],
            [['dp_pembayaran', 'alamat_pelanggan', 'alamat_proyek', 'rencana_pembangunan', 'rencana_survey', 'created_at', 'updated_at', 'deleted_at', 'list_ruangan', 'tanggal_pembayaran'], 'safe'],
            [['keterangan', 'kode_proyek', 'dokumen_tor', 'nomor_spk', 'boq_proyek', 'keterangan_pembayaran', 'informasi_proyek', 'bukti-pembayaran', 'alasan_tolak'], 'string'],
            [['kode_unik'], 'unique'],
            [['id_wilayah_provinsi'], 'string', 'max' => 2],
            [['id_wilayah_kota'], 'string', 'max' => 4],
            [['id_wilayah_kecamatan'], 'string', 'max' => 7],
            [['id_wilayah_desa'], 'string', 'max' => 10],
            [['nama_awal', 'nama_akhir'], 'string', 'max' => 80],
            [['no_hp'], 'string', 'max' => 20],
            [['label', 'alamat_pelanggan', 'alamat_proyek'], 'string', 'max' => 255],
            [['panjang', 'lebar'], 'string', 'max' => 50],
            [['budget', 'luas_tanah'], 'string', 'max' => 25],
            [['id_konsep_design'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterKonsepDesain::className(), 'targetAttribute' => ['id_konsep_design' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['id_user' => 'id']],
            [['id_lantai'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterLantai::className(), 'targetAttribute' => ['id_lantai' => 'id']],
            [['id_wilayah_provinsi'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahProvinsi::className(), 'targetAttribute' => ['id_wilayah_provinsi' => 'id']],
            [['id_wilayah_kota'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKota::className(), 'targetAttribute' => ['id_wilayah_kota' => 'id']],
            [['id_wilayah_kecamatan'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKecamatan::className(), 'targetAttribute' => ['id_wilayah_kecamatan' => 'id']],
            [['id_wilayah_desa'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahDesa::className(), 'targetAttribute' => ['id_wilayah_desa' => 'id']],
            [['id_satuan'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterSatuan::className(), 'targetAttribute' => ['id_satuan' => 'id']],
            [['created_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['created_by' => 'id']],
            [['updated_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['updated_by' => 'id']],
            [['deleted_by'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['deleted_by' => 'id']],
            [['id_penawaran'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Penawaran::className(), 'targetAttribute' => ['id_penawaran' => 'id']],
            [['id_proyek'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Proyek::className(), 'targetAttribute' => ['id_proyek' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_satuan' => 'Satuan',
            'id_konsep_design' => 'Konsep Design',
            'id_penawaran' => 'Penawaran',
            'id_user' => 'User',
            'id_lantai' => 'Lantai',
            'id_wilayah_provinsi' => 'Provinsi',
            'id_wilayah_kota' => 'Kota',
            'id_wilayah_kecamatan' => 'Kecamatan',
            'id_wilayah_desa' => 'Desa',
            'id_kontraktor' => 'Kontraktor',
            'nama_awal' => 'Nama Awal',
            'nama_akhir' => 'Nama Akhir',
            'no_hp' => 'No HP',
            'label' => 'Nama Proyek',
            'panjang' => 'Panjang Tanah',
            'lebar' => 'Lebar Tanah',
            'budget' => 'Anggaran',
            'luas_tanah' => 'Luas Tanah(m2)',
            'rencana_pembangunan' => 'Rencana Pembangunan',
            'rencana_survey' => 'Rencana Survei',
            'alamat_pelanggan' => 'Detail Alamat Pelanggan',
            'alamat_proyek' => 'Detail Alamat Proyek',
            'alasan_tolak' => 'Alasan Tolak',
            'alasan_tolak_tor' => 'Alasan Tolak TOR',
            'dp_pembayaran' => 'Atur DP',
            'tanggal_pembayaran' => 'Tanggal Pembayaran',
            'bayar_dp' => 'Bayar DP',
            'bukti_pembayaran' => 'Bukti Pembayaran',
            'keterangan_pembayaran' => 'Keterangan Pembayaran',
            'status_pembayaran' => 'Status Pembayaran',
            'keterangan' => 'Keterangan',
            'created_at' => 'Dibuat pada',
            'updated_at' => 'Diubah Pada',
            'deleted_at' => 'Dihapus pada',
            'created_by' => 'Dibuat oleh',
            'updated_by' => 'Diubah oleh',
            'deleted_by' => 'Dihapus oleh',
            'flag' => 'Flag',
            'status' => 'Status Isian Lanjutan',
            'boq_proyek' => 'Documen BOQ',
            'nomor_spk' => 'Nomor SPK',
            'informasi_proyek' => 'Informasi Proyek',
            'status_boq' => 'Status BOQ',
            'is_beli_material' => 'Pembelian Material',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHasilKonsultasis()
    {
        return $this->hasMany(\app\models\HasilKonsultasi::className(), ['id_isian_lanjutan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKonsepDesign()
    {
        return $this->hasOne(\app\models\MasterKonsepDesain::className(), ['id' => 'id_konsep_design']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLantai()
    {
        return $this->hasOne(\app\models\MasterLantai::className(), ['id' => 'id_lantai']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahProvinsi()
    {
        return $this->hasOne(\app\models\WilayahProvinsi::className(), ['id' => 'id_wilayah_provinsi']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahKota()
    {
        return $this->hasOne(\app\models\WilayahKota::className(), ['id' => 'id_wilayah_kota']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahKecamatan()
    {
        return $this->hasOne(\app\models\WilayahKecamatan::className(), ['id' => 'id_wilayah_kecamatan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahDesa()
    {
        return $this->hasOne(\app\models\WilayahDesa::className(), ['id' => 'id_wilayah_desa']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSatuan()
    {
        return $this->hasOne(\app\models\MasterSatuan::className(), ['id' => 'id_satuan']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCreatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'created_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUpdatedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'updated_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDeletedBy()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'deleted_by']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPenawaran()
    {
        return $this->hasOne(\app\models\Penawaran::className(), ['id' => 'id_penawaran']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIsianLanjutanRuangans()
    {
        return $this->hasMany(\app\models\IsianLanjutanRuangan::className(), ['id_isian_lanjutan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIsianLanjutanRuangans0()
    {
        return $this->hasMany(\app\models\IsianLanjutanRuangan::className(), ['id_isian_lanjutan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKonsultasis()
    {
        return $this->hasMany(\app\models\Konsultasi::className(), ['id_isian_lanjutan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    // public function getMasterMenus()
    // {
    //     return $this->hasMany(\app\models\MasterMenu::className(), ['form_menu_id' => 'id']);
    // }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPenawarans()
    {
        return $this->hasMany(\app\models\Penawaran::className(), ['id_isian_lanjutan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKontraktors()
    {
        return $this->hasOne(\app\models\Kontraktor::className(), ['id' => 'id_kontraktor']);
    }



    /**
     * @inheritdoc
     * @return \app\models\query\IsianLanjutanQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\IsianLanjutanQuery(get_called_class());
    }



    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            // 'id_satuan',
            'id_konsep_design',
            'id_penawaran',
            'is_beli_material',
            'id_user',
            'id_lantai',
            'id_wilayah_provinsi',
            'id_wilayah_kota',
            'id_wilayah_kecamatan',
            'id_wilayah_desa',
            'id_kontraktor',
            'nama_awal',
            'nama_akhir',
            'no_hp',
            'label',
            'panjang',
            'lebar',
            'budget',
            // 'luas_tanah',
            'latitude',
            'longitude',
            // 'rencana_pembangunan',
            // 'rencana_survey',
            'keterangan',
            'alamat_pelanggan',
            'alamat_proyek',
            'created_at',
            'updated_at',
            'deleted_at',
            'created_by',
            'updated_by',
            'deleted_by',
            'boq_proyek',
            'nomor_spk',
            'informasi_proyek',
            'status_boq',
            'flag',
            'status',
        ];

        $delete = [
            'deleted_by',
            'flag',
        ];

        $columns_init = [
            // 'id',
            'id_user',
            'nama_awal',
            // 'nama_akhir',
        ];

        $columns_survey = [
            "rencana_survey"
        ];

        $columns_bangun = [
            "rencana_pembangunan",
            "alasan_tolak",
            "status"
        ];

        $columns_deal = [
            "id_penawaran",
            "status"
        ];

        $columns_tolak = [
            "status",
            "alasan_tolak",
            "approval_dokumen_tor"
        ];

        $columns_batal = [
            "status",
            "alasan_tolak",
        ];

        $columns_revisi = [
            "rencana_pembangunan",
            "status",
            "alasan_tolak",
        ];

        $upload_tor = [
            "dokumen_tor",
            "alasan_tolak",
        ];

        $approve_tor = [
            "status"
        ];

        $dp = [
            'dp_pembayaran',
        ];

        $pembayaran = [
            'bukti_pembayaran',
            'tanggal_pembayaran',
            'keterangan_pembayaran',
            'status_pembayaran',
            'alasan_tolak',
        ];

        $konfirmasi = [
            'status_pembayaran',
            'alasan_tolak'
        ];

        $tolak = [
            'status_pembayaran',
            'keterangan_pembayaran',
            'alasan_tolak'
        ];

        $dp_ulang = [
            'bukti_pembayaran',
            'tanggal_pembayaran',
            'keterangan_pembayaran',
            'status_pembayaran',
        ];

        $columns_deal_rencana_pembangunan = [
            "id_proyek",
            "kode_proyek",
            "approval_dokumen_tor",
            "alasan_tolak",
            "status"
        ];

        $status_boq = [
            'status_boq',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        $parent[static::SCENARIO_DELETE] = $delete;
        $parent[static::SCENARIO_SURVEY] = $columns_survey;
        $parent[static::SCENARIO_BANGUN] = $columns_bangun;
        $parent[static::SCENARIO_DEAL] = $columns_deal;
        $parent[static::SCENARIO_TOLAK] = $columns_tolak;
        $parent[static::SCENARIO_REVISI_RENCANA_PEMBANGUNAN] = $columns_revisi;
        $parent[static::SCENARIO_BATAL_PROYEK] = $columns_batal;
        $parent[static::SCENARIO_INITIAL_CREATE] = $columns_init;
        $parent[static::SCENARIO_UPLOAD_TOR] = $upload_tor;
        $parent[static::SCENARIO_APPROVE_TOR] = $approve_tor;
        $parent[static::SCENARIO_DP] = $dp;
        $parent[static::SCENARIO_BAYARDP] = $pembayaran;
        $parent[static::SCENARIO_KONFIRMASI] = $konfirmasi;
        $parent[static::SCENARIO_TOLAK_DP] = $tolak;
        $parent[static::SCENARIO_BAYARDPULANG] = $dp_ulang;
        $parent[static::SCENARIO_DEAL_RENCANA_PEMBANGUNAN] = $columns_deal_rencana_pembangunan;
        $parent[static::SCENARIO_STATUS_BOQ] = $status_boq;
        return $parent;
    }

    public function setRender($arr)
    {
        $this->_render = array_merge($this->_render, $arr);
    }

    public function removeRender($arr)
    {
        unset($this->_render[$arr]);
    }

    /**
     * Simplify return data xD
     */
    public function render()
    {
        return array_merge($this->_render, [
            "model" => $this,
        ]);
    }

    /**
     * override validate
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors);
    }

    /**
     * override load
     */
    public function load($data, $formName = null, $service = "web")
    {
        return parent::load($data, $formName);
    }
}
