<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "t_kontraktor_detail".
 *
 * @property integer $id
 * @property integer $id_kontraktor
 * @property integer $id_user
 *
 * @property \app\models\Kontraktor $kontraktor
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class KontraktorDetail extends \yii\db\ActiveRecord
{



    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if (isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function ($model) {
                return $model->id;
            };
        endif;
        if (isset($parent['id_kontraktor'])) :
            unset($parent['id_kontraktor']);
            $parent['id_kontraktor'] = function ($model) {
                return $model->id_kontraktor;
            };
            $parent['_kontraktor'] = function ($model) {
                $rel = $model->kontraktor;
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_user'])) :
            unset($parent['id_user']);
            $parent['id_user'] = function ($model) {
                return $model->id_user;
            };
            $parent['_user'] = function ($model) {
                $rel = $model->user;
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;



        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_kontraktor_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // [['id_user'], 'required'],
            [['id_kontraktor', 'id_user'], 'integer'],
            [['id_kontraktor'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Kontraktor::className(), 'targetAttribute' => ['id_kontraktor' => 'id']],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['id_user' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_kontraktor' => 'Kontraktor',
            'id_user' => 'Pengguna',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKontraktor()
    {
        return $this->hasOne(\app\models\Kontraktor::className(), ['id' => 'id_kontraktor']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'id_user']);
    }



    /**
     * @inheritdoc
     * @return \app\models\query\KontraktorDetailQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\KontraktorDetailQuery(get_called_class());
    }



    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'id_kontraktor',
            'id_user',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    public function setRender($arr)
    {
        $this->_render = array_merge($this->_render, $arr);
    }

    public function removeRender($arr)
    {
        unset($this->_render[$arr]);
    }

    /**
     * Simplify return data xD
     */
    public function render()
    {
        return array_merge($this->_render, [
            "model" => $this,
        ]);
    }

    /**
     * override validate
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors);
    }

    /**
     * override load
     */
    public function load($data, $formName = null, $service = "web")
    {
        return parent::load($data, $formName);
    }
}
