<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "t_master_satuan".
 *
 * @property integer $id
 * @property string $nama
 * @property string $keterangan
 * @property integer $jenis_satuan_id
 * @property integer $flag
 *
 * @property \app\models\TIsianLanjutan[] $tIsianLanjutans
 * @property \app\models\TMasterMaterial[] $tMasterMaterials
 * @property \app\models\TMasterJenisSatuan $jenisSatuan
 * @property string $aliasModel
 */
abstract class MasterSatuan extends \yii\db\ActiveRecord
{



    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if (isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function ($model) {
                return $model->id;
            };
        endif;
        if (isset($parent['nama'])) :
            unset($parent['nama']);
            $parent['nama'] = function ($model) {
                return $model->nama;
            };
        endif;
        if (isset($parent['keterangan'])) :
            unset($parent['keterangan']);
            $parent['keterangan'] = function ($model) {
                return $model->keterangan;
            };
        endif;
        if (isset($parent['jenis_satuan_id'])) :
            unset($parent['jenis_satuan_id']);
            $parent['jenis_satuan_id'] = function ($model) {
                return $model->jenis_satuan_id;
            };
            $parent['_jenis_satuan'] = function ($model) {
                $rel = $model->jenisSatuan;
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['flag'])) :
            unset($parent['flag']);
            $parent['flag'] = function ($model) {
                return $model->flag;
            };
        endif;


        // $parent['t_isian_lanjutan'] = function($model) {
        //     $rel = $model->tIsianLanjutans;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };
        // $parent['t_master_material'] = function($model) {
        //     $rel = $model->tMasterMaterials;
        //     if($rel) :
        //         return $rel;
        //     endif;
        //     return null;
        // };

        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_master_satuan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'keterangan'], 'required'],
            [['jenis_satuan_id', 'flag'], 'integer'],
            [['nama'], 'string', 'max' => 20],
            [['keterangan'], 'string', 'max' => 100],
            [['jenis_satuan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterJenisSatuan::className(), 'targetAttribute' => ['jenis_satuan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'keterangan' => 'Keterangan',
            'jenis_satuan_id' => 'Jenis Satuan',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTIsianLanjutans()
    {
        return $this->hasMany(\app\models\IsianLanjutan::className(), ['id_satuan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTMasterMaterials()
    {
        return $this->hasMany(\app\models\MasterMaterial::className(), ['id_satuan' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisSatuan()
    {
        return $this->hasOne(\app\models\MasterJenisSatuan::className(), ['id' => 'jenis_satuan_id']);
    }


    public static function find()
    {
        return new \app\models\query\MasterSatuanQuery(get_called_class());
    }



    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'nama',
            'keterangan',
            'jenis_satuan_id',
            'flag',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    public function setRender($arr)
    {
        $this->_render = array_merge($this->_render, $arr);
    }

    public function removeRender($arr)
    {
        unset($this->_render[$arr]);
    }

    /**
     * Simplify return data xD
     */
    public function render()
    {
        return array_merge($this->_render, [
            "model" => $this,
        ]);
    }

    /**
     * override validate
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors);
    }

    /**
     * override load
     */
    public function load($data, $formName = null, $service = "web")
    {
        return parent::load($data, $formName);
    }
}
