<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "t_profile_tukang".
 *
 * @property integer $id
 * @property integer $id_user
 * @property integer $id_layanan
 * @property string $nama
 * @property string $foto_ktp
 * @property string $keahlian
 * @property string $alamat
 * @property integer $flag
 *
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class ProfileTukang extends \yii\db\ActiveRecord
{

    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if (isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function ($model) {
                return $model->id;
            };
        endif;
        if (isset($parent['id_user'])) :
            unset($parent['id_user']);
            $parent['id_user'] = function ($model) {
                return $model->id_user;
            };
            $parent['_user'] = function ($model) {
                $rel = $model->user;
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['id_layanan'])) :
            unset($parent['id_layanan']);
            $parent['id_layanan'] = function ($model) {
                return $model->id_layanan;
            };
            $parent['_layanan'] = function ($model) {
                return $model->getLayananLabel();
            };
        endif;
        if (isset($parent['nama'])) :
            unset($parent['nama']);
            $parent['nama'] = function ($model) {
                return $model->nama;
            };
        endif;
        if (isset($parent['foto_ktp'])) :
            unset($parent['foto_ktp']);
            $parent['foto_ktp'] = function ($model) {
                return \Yii::$app->formatter->asMyimage($model->foto_ktp, false);
            };
        endif;
        if (isset($parent['keahlian'])) :
            unset($parent['keahlian']);
            $parent['keahlian'] = function ($model) {
                return $model->keahlian;
            };
        endif;
        if (isset($parent['alamat'])) :
            unset($parent['alamat']);
            $parent['alamat'] = function ($model) {
                return $model->alamat;
            };
        endif;
        if (isset($parent['flag'])) :
            unset($parent['flag']);
        // $parent['flag'] = function ($model) {
        //     return $model->flag;
        // };
        endif;



        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 't_profile_tukang';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_user', 'nama', 'foto_ktp', 'keahlian', 'alamat'], 'required'],
            [['id_user', 'flag'], 'integer'],
            [['alamat'], 'string'],
            [['id_layanan'], 'safe'],
            [['nama'], 'string', 'max' => 200],
            [['foto_ktp', 'keahlian'], 'string', 'max' => 255],
            [['id_user'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['id_user' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('cruds', 'ID'),
            'id_user' => Yii::t('cruds', 'User'),
            'id_layanan' => Yii::t('cruds', 'Layanan'),
            'nama' => Yii::t('cruds', 'Nama'),
            'foto_ktp' => Yii::t('cruds', 'Foto Ktp'),
            'keahlian' => Yii::t('cruds', 'Keahlian'),
            'alamat' => Yii::t('cruds', 'Alamat'),
            'flag' => Yii::t('cruds', 'Flag'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'id_user']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLayanan()
    {
        return $this->hasOne(\app\models\MasterKategoriLayananSameday::className(), ['id' => 'id_layanan']);
    }



    /**
     * @inheritdoc
     * @return \app\models\query\ProfileTukangQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \app\models\query\ProfileTukangQuery(get_called_class());
    }



    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'id_user',
            'id_layanan',
            'nama',
            'foto_ktp',
            'keahlian',
            'alamat',
            'flag',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    public function setRender($arr)
    {
        $this->_render = array_merge($this->_render, $arr);
    }

    public function removeRender($arr)
    {
        unset($this->_render[$arr]);
    }

    /**
     * Simplify return data xD
     */
    public function render()
    {
        return array_merge($this->_render, [
            "model" => $this,
        ]);
    }

    /**
     * override validate
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors);
    }

    /**
     * override load
     */
    public function load($data, $formName = null, $service = "web")
    {
        return parent::load($data, $formName);
    }
}
