<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build
// Modified by Defri Indra
// 2021

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tentang_homei_detail".
 *
 * @property integer $id
 * @property integer $id_tentang_homei
 * @property string $icon
 * @property string $judul
 * @property string $isi
 *
 * @property \app\models\TentangHomei $tentangHomei
 * @property string $aliasModel
 */
abstract class TentangHomeiDetail extends \yii\db\ActiveRecord
{



    const SCENARIO_CREATE = 'create';
    const SCENARIO_UPDATE = 'update';
    public $_render = [];

    /**
     * @inheiritance
     */
    public function fields()
    {
        $parent = parent::fields();

        if (isset($parent['id'])) :
            unset($parent['id']);
            $parent['id'] = function ($model) {
                return $model->id;
            };
        endif;
        if (isset($parent['id_tentang_homei'])) :
            unset($parent['id_tentang_homei']);
            $parent['id_tentang_homei'] = function ($model) {
                return $model->id_tentang_homei;
            };
            $parent['_tentang_homei'] = function ($model) {
                $rel = $model->tentangHomei;
                if ($rel) :
                    return $rel;
                endif;
                return null;
            };
        endif;
        if (isset($parent['icon'])) :
            unset($parent['icon']);
            $parent['icon'] = function ($model) {
                return \Yii::$app->formatter->asMyimage($model->icon, false);
            };
        endif;
        if (isset($parent['judul'])) :
            unset($parent['judul']);
            $parent['judul'] = function ($model) {
                return $model->judul;
            };
        endif;
        if (isset($parent['isi'])) :
            unset($parent['isi']);
            $parent['isi'] = function ($model) {
                return $model->isi;
            };
        endif;



        return $parent;
    }

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tentang_homei_detail';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_tentang_homei', 'icon', 'judul', 'isi'], 'required'],
            [['id_tentang_homei'], 'integer'],
            [['isi'], 'string'],
            [['icon', 'judul'], 'string', 'max' => 50],
            [['id_tentang_homei'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\TentangHomei::className(), 'targetAttribute' => ['id_tentang_homei' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_tentang_homei' => 'Tentang HOMEI',
            'icon' => 'Ikon',
            'judul' => 'Judul',
            'isi' => 'Isi',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTentangHomei()
    {
        return $this->hasOne(\app\models\TentangHomei::className(), ['id' => 'id_tentang_homei']);
    }





    public function scenarios()
    {
        $parent = parent::scenarios();

        $columns = [
            'id',
            'id_tentang_homei',
            'icon',
            'judul',
            'isi',
        ];

        $parent[static::SCENARIO_CREATE] = $columns;
        $parent[static::SCENARIO_UPDATE] = $columns;
        return $parent;
    }

    public function setRender($arr)
    {
        $this->_render = array_merge($this->_render, $arr);
    }

    public function removeRender($arr)
    {
        unset($this->_render[$arr]);
    }

    /**
     * Simplify return data xD
     */
    public function render()
    {
        return array_merge($this->_render, [
            "model" => $this,
        ]);
    }

    /**
     * override validate
     */
    public function validate($attributeNames = null, $clearErrors = true)
    {
        return parent::validate($attributeNames, $clearErrors);
    }

    /**
     * override load
     */
    public function load($data, $formName = null, $service = "web")
    {
        return parent::load($data, $formName);
    }
}
