<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\SupplierSearch $searchModel
 */

$this->title = 'Supplier';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?= Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
</p>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{pager}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            \app\components\ActionButton::getButtons([
                                'template' => '{view} {update} {delete} {rekomendasi}',
                                'buttons' => [
                                    'rekomendasi' => function ($url, $model, $key) {
                                        if ($model->rekomendasi_homei != 1) {
                                            // var_dump($model->rekomendasi_homei);die;
                                            return Html::a("<i class='fa fa-check'></i>", ["rekomendasi", "id" => $model->id], [
                                                "class" => "mr-1 mb-1 btn btn-success",
                                                "title" => "Rekomendasi Supplier",
                                                "data-confirm" => "Apakah Anda yakin ingin mengaktifkan Rekomendasi untuk supplier ini ?",
                                                //"data-method" => "GET"
                                            ]);
                                        } else {
                                            return Html::a("<i class='fa fa-window-close'></i>", ["non-rekomendasi", "id" => $model->id], [
                                                "class" => "mr-1 mb-1 btn btn-danger",
                                                "title" => "Rekomendasi Supplier",
                                                "data-confirm" => "Apakah Anda yakin ingin menonaktifkan Rekomendasi untuk supplier ini ?",
                                                //"data-method" => "GET"
                                            ]);
                                        }
                                    },
                                ]
                            ]),

                            // modified by Defri Indra
                            [
                                'class' => yii\grid\DataColumn::className(),
                                'attribute' => 'id_provinsi',
                                'value' => function ($model) {
                                    if ($rel = $model->provinsi) {
                                        return $rel->nama;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            // modified by Defri Indra
                            [
                                'class' => yii\grid\DataColumn::className(),
                                'attribute' => 'id_kota',
                                'value' => function ($model) {
                                    if ($rel = $model->kota) {
                                        return $rel->nama;
                                    } else {
                                        return '';
                                    }
                                },
                                'format' => 'raw',
                            ],
                            [
                                'attribute' => 'nama_supplier',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'alamat',
                                'format' => 'ntext',
                            ],
                            [
                                'attribute' => 'telepon',
                                'format' => 'text',
                            ], [
                                'attribute' => 'rekomendasi_homei',
                                'format' => 'boolean',
                            ],
                            // 		[
                            //     'attribute' => 'latitude',
                            //     'format' => 'text',
                            // ],
                            // 		[
                            //     'attribute' => 'longitude',
                            //     'format' => 'text',
                            // ],
                            /*[
            'attribute' => 'created_at',
            'format' => 'iddate',
        ],*/
                            /*[
            'attribute' => 'updated_at',
            'format' => 'iddate',
        ],*/
                            /*[
            'attribute' => 'deleted_at',
            'format' => 'iddate',
        ],*/
                            /*// modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'created_by',
                        'value' => function ($model) {
                            if ($rel = $model->createdBy) {
                                return $rel->name;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],*/
                            /*// modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'updated_by',
                        'value' => function ($model) {
                            if ($rel = $model->updatedBy) {
                                return $rel->name;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],*/
                            /*// modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'deleted_by',
                        'value' => function ($model) {
                            if ($rel = $model->deletedBy) {
                                return $rel->name;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],*/
                            /*[
            'attribute' => 'flag',
            'format' => 'boolean',
        ],*/
                            /*[
            'attribute' => 'rekomendasi_homei',
            'format' => 'text',
        ],*/
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>