<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use \dmstr\helpers\Html;
use app\components\annex\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\search\ProyekSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>
<div class="accordion" id="accordionExample">
	<div class="card shadow-none" style="background: transparent;">
		<div class="card-header" id="headingOne" style="background: transparent;">
			<h5 class="m-0">
				<button class="btn btn-default" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					Pencarian
				</button>
			</h5>
		</div>
		<div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
			<div class="card-body bg-white">

				<?php $form = ActiveForm::begin([
					'action' => ['index'],
					'layout' => 'horizontal',
					'method' => 'get',
				]); ?>
				<div class="d-flex  flex-wrap">
					<?= $form->field($model, 'nama_proyek', \app\components\Constant::COLUMN(1)) ?>
				</div>
				<div class="clearfix"></div>
				<div class="col-md-12">
					<div class="col-md-12">
						<div class="form-group">
							<?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
						</div>
					</div>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>