<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;

// The widget
use kartik\select2\Select2; // or kartik\select2\Select2
use yii\web\JsExpression;

// The controller action that will render the list
$url = \yii\helpers\Url::to(['user/get-user']);

/**
 * @var yii\web\View $this
 * @var app\models\Smarthome $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'id' => 'Smarthome',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <?= $form->field($model, 'id_user', \app\components\Constant::COLUMN())->widget(Select2::classname(), [
        'data' => \yii\helpers\ArrayHelper::map(app\models\User::find()->where(['flag' => 1, 'role_id' => 3])->limit(10)->all(), 'id', 'name'),
        'options' => ['multiple' => false],
        'name' => 'class_name',
        'model' => $model,
        'attribute' => 'id_user',
        'pluginOptions' => [
            'allowClear' => true,
            'minimumInputLength' => 3,
            'language' => [
                'errorLoading' => new JsExpression("function () { return 'Menunggu hasil...'; }"),
            ],
            'ajax' => [
                'url' => $url,
                'dataType' => 'json',
                'data' => new JsExpression('function(params) { return {q:params.term}; }')
            ],
            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
            'templateResult' => new JsExpression('function(user) { return user.text; }'),
            'templateSelection' => new JsExpression('function (user) { return user.text; }'),
        ],
    ]); ?>
    <?= $form->field($model, 'nama', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <?php // $form->field($model, 'suhu', \app\components\Constant::COLUMN())->textInput(['maxlength' => true, 'readonly' => true]) ?>
    <?php // $form->field($model, 'kelembapan', \app\components\Constant::COLUMN())->textInput(['maxlength' => true, 'readonly' => true]) ?>
    <?php // $form->field($model, 'tegangan', \app\components\Constant::COLUMN())->textInput(['maxlength' => true, 'readonly' => true]) ?>
    <?php // $form->field($model, 'daya', \app\components\Constant::COLUMN())->textInput(['maxlength' => true, 'readonly' => true]) ?>
    <?php // $form->field($model, 'ampere', \app\components\Constant::COLUMN())->textInput(['maxlength' => true, 'readonly' => true]) ?>
    <?= $form->field($model, 'token', \app\components\Constant::COLUMN(1))->textInput(['maxlength' => true, 'readonly' => true, "placeholder" => "Token di generate otomatis"]) ?>
    <div class="clearfix"></div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>