<?php
/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\annex\Tabs;

/**
* @var yii\web\View $this
* @var app\models\MasterKonsepDesain $model
*/

$this->title = 'Master Konsep Desain : ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Master Konsep Desain', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud master-konsep-desain-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Master Konsep Desain', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-12">
            <div class="card m-b-30">
                <div class="card-body">
                    <?php $this->beginBlock('app\models\MasterKonsepDesain'); ?>

                    <?= DetailView::widget([
                        'model' => $model,
                        'attributes' => [
					        [
            'attribute' => 'nama_konsep',
            'format' => 'text',
        ],
					        [
            'attribute' => 'gambar',
            'format' => 'myImage',
        ],
					        [
            'attribute' => 'flag',
            'format' => 'boolean',
        ],
                        ],
                    ]); ?>

                    <hr/>

                    <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
                    [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                    ]); ?>
                    <?php $this->endBlock(); ?>


                    
<?php $this->beginBlock('IsianLanjutans'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
  <?= Html::a(
                                    '<span class="glyphicon glyphicon-list"></span> ' . 'Semua Data' . ' Isian Lanjutans',
                                    ['isian-lanjutan/index'],
                                    ['class'=>'btn text-muted btn-xs']
                                ) ?>
  <?= Html::a(
                                    '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Isian Lanjutan',
                                    ['isian-lanjutan/create', 'IsianLanjutan' => ['Array' => $model->id]],
                                    ['class'=>'btn btn-success btn-xs']
                                ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-IsianLanjutans', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-IsianLanjutans ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("defrindr")}']]) ?>
<?= '<div class="table-responsive">'
 .                     \yii\grid\GridView::widget([
                        'layout' => '{summary}{pager}<br/>{items}{pager}',
                        'dataProvider' => new \yii\data\ActiveDataProvider([
                            'query' => $model->getIsianLanjutans(),
                            'pagination' => [
                                'pageSize' => 20,
                                'pageParam'=>'page-isianlanjutans',
                            ]
                        ]),
                        'pager'        => [
                            'class'          => \app\components\annex\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'columns' => [
                     [
                        'class'      => 'yii\grid\ActionColumn',
                        'template'   => '{view} {update}',
                        'contentOptions' => ['nowrap'=>'nowrap'],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            // using the column name as key, not mapping to 'id' like the standard generator
                            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                            $params[0] = 'isian-lanjutan' . '/' . $action;
                            $params['IsianLanjutan'] = ['id_konsep_design' => $model->primaryKey()[0]];
                            return $params;
                        },
                        'buttons'    => [
                            
                        ],
                        'controller' => 'isian-lanjutan'
                    ],
                    // modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'id_satuan',
                        'value' => function ($model) {
                            if ($rel = $model->satuan) {
                                return $rel->nama;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    // modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'id_provinsi',
                        'value' => function ($model) {
                            if ($rel = $model->provinsi) {
                                return $rel->nama;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    // modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'id_kota',
                        'value' => function ($model) {
                            if ($rel = $model->kota) {
                                return $rel->nama;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    // modified by Defri Indra
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'id_penawaran',
                        'value' => function ($model) {
                            if ($rel = $model->penawaran) {
                                return $rel->id;
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
        [
            'attribute' => 'panjang',
            'format' => 'text',
        ],
        [
            'attribute' => 'lebar',
            'format' => 'text',
        ],
        [
            'attribute' => 'budget',
            'format' => 'text',
        ],
        [
            'attribute' => 'keterangan',
            'format' => 'text',
        ],
        [
            'attribute' => 'created_at',
            'format' => 'iddate',
        ],
]
                    ])
 . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


                    <?= Tabs::widget(
                    [
                        'id' => 'relation-tabs',
                        'encodeLabels' => false,
                        'items' => [ 
                                                [
                        'label'   => '<b class=""># '.$model->id.'</b>',
                        'content' => $this->blocks['app\models\MasterKonsepDesain'],
                        'active'  => true,
                    ],                        [
                            'content' => $this->blocks['IsianLanjutans'],
                            'label'   => '<small>Isian Lanjutans <span class="badge badge-default">'.count($model->getIsianLanjutans()->asArray()->all()).'</span></small>',
                            'active'  => false,
                        ],
                        ]
                    ]);
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
