<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;
use kartik\file\FileInput;

/**
 * @var yii\web\View $this
 * @var app\models\ProyekGaleri $model
 * @var app\components\annex\ActiveForm $form
 */

?>

<?php $form = ActiveForm::begin([
    'action' => \yii\helpers\Url::current(["id_project" => $model->id_proyek]),
    'id' => 'ProyekGaleri',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

    <div class="clearfix"></div>
    <div class="col-md-12 text-center">
        <?= Yii::$app->formatter->asMyImage($model->nama_file) ?>
    </div>
    <div class="clearfix"></div>
    <?=
    $form->field($model, 'id_proyek', ['template' => '{input}'])->hiddenInput()->label(false); ?>
    <?= $form->field($model, 'id_proyek_kemajuan', \app\components\Constant::COLUMN(1))->widget(\kartik\select2\Select2::classname(), [
        'name' => 'id_proyek_kemajuan',
        'model' => $model,
        'attribute' => 'id_proyek_kemajuan',
        'data' => \yii\helpers\ArrayHelper::map(app\models\ProyekKemajuan::find()->where(['id_proyek' => $model->id_proyek])->all(), 'id', 'item'),
        'options' => [
            'prompt' => $model->getAttributeLabel('id_proyek_kemajuan'),
            'multiple' => false,
            'disabled' => (isset($relAttributes) && isset($relAttributes['id_proyek_kemajuan'])),
        ],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>
    <?= $form->field($model, 'nama_file', \app\components\Constant::COLUMN())->widget(FileInput::class, []) ?>
    <?= $form->field($model, 'keterangan', \app\components\Constant::COLUMN())->textarea(['rows' => 6]) ?>
    <div class="clearfix"></div>
</div>
<hr />
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['/proyek/view', 'id' => $model->id_proyek], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>