<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\Constant;
use yii\data\ActiveDataFilter;
use yii\data\ActiveDataProvider;
use \dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\ProyekKeuanganKeluarSearch $searchModel
 */
?>

<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="table-responsive">
    <?= GridView::widget([
        'layout' => '{summary}{pager}{items}{pager}',
        'dataProvider' => new ActiveDataProvider([
            'query' => $model->getProyekKeuanganKeluars()
                ->andWhere(['tipe' => 1]) // tipe purchase order
                ->andWhere(['is', 'deleted_at', null])
                ->orderBy('created_at DESC'),
        ]),
        'pager'        => [
            'class'          => app\components\annex\LinkPager::className(),
            'firstPageLabel' => 'First',
            'lastPageLabel'  => 'Last'
        ],
        'filterModel' => $searchModel,
        'tableOptions' => ['class' => 'table table-bordered table-hover'],
        'headerRowOptions' => ['class' => 'x'],
        'columns' => [

            \app\components\ActionButton::getButtons([
                'template' => "{view} {bayar}",
                'buttons' => [
                    'view' => function ($url, $model, $key) {
                        $url = \yii\helpers\Url::to([
                            '/proyek-keuangan-keluar/view',
                            'id' => $model->id,
                            "id_project" => $model->id_proyek,
                        ]);
                        return Html::button("<i class='fa fa-eye'></i>", [
                            "class" => "mr-1 mb-1 btn btn-success",
                            "title" => "Lihat Detail",
                            'onclick' => new \yii\web\JsExpression("openmodal( '$url',  'Detail')")
                        ]);
                    },
                    'bayar' => function ($url, $model, $key) {
                        if ($model->status == 2) return "";
                        $params[] = "/proyek-keuangan-keluar-bayar/create";
                        $params["ProyekKeuanganKeluarBayar"] = [
                            "id_proyek" => $model->id_proyek,
                            "id_keuangan_keluar" => $model->id,
                        ];
                        $params["id_project"] = $model->id_proyek;
                        $params = Url::to($params);
                        return Html::button("<i class='fa fa-money'></i>", [
                            "class" => "mr-1 mb-1 btn btn-primary",
                            "title" => "Lihat Detail",
                            'onclick' => new \yii\web\JsExpression("openmodal( '$params',  'Bayar')")
                        ]);
                    },
                ]
            ]),
            [
                'attribute' => 'no_invoice',
                'format' => 'text',
            ],
            [
                'attribute' => 'no_po',
                'format' => 'text',
            ],
            [
                'attribute' => 'id_kategori',
                'format' => 'raw',
                'value' => function ($model) {
                    return $model->kategori->nama_kategori;
                }
            ],
            // [
            //     'attribute' => 'detail',
            //     'format' => 'raw',
            //     'value' => function ($model) {
            //         $count = $model->getProyekKeuanganKeluarDetails()->count();
            //         if ($count > 1) {
            //             $detail = implode(",", $model->getProyekKeuanganKeluarDetails()->select('item')->column());
            //             if (strlen($detail) > 50) {
            //                 $detail = substr($detail, 0, 50) . "...";
            //             }
            //         } else {
            //             $detail = implode(",", $model->getProyekKeuanganKeluarDetails()->select('item')->column());
            //         }
            //         return $detail;
            //     }
            // ],
            // [
            //     'attribute' => 'qty',
            //     'label' => 'Kuantitas',
            //     'format' => 'raw',
            //     'value' => function ($model) {
            //         $count = $model->getProyekKeuanganKeluarDetails()->count();
            //         if ($count > 1) {
            //             $detail = Html::button('Detail', [
            //                 'value' => Url::to(['/proyek-keuangan-keluar/detail', 'id' => $model->id]),
            //                 'style' => 'border:0;background:transparent'
            //             ]);
            //         } else {
            //             $detail = implode(",", $model->getProyekKeuanganKeluarDetails()->select('kuantitas')->column());
            //         }
            //         return $detail;
            //     }
            // ],
            // [
            //     'attribute' => 'tanggal',
            //     'format' => 'iddate',
            // ],
            [
                'attribute' => 'total_jumlah',
                'format' => 'rp',
            ],
            [
                'attribute' => 'vendor',
                'format' => 'text',
            ],
            // [
            //     'attribute' => 'keterangan',
            //     'format' => 'ntext',
            // ],
            // [
            //     'attribute' => 'dokumen_po',
            //     'format' => 'download',
            // ],
            [
                'attribute' => 'status',
                'value' => function ($model) {
                    return $model->getStatus();
                },
            ],
            \app\components\ActionButton::getButtons([
                'template' => "{update} {delete}",
                'buttons' => [
                    'update' => function ($url, $model, $key) {
                        return Html::button("<i class='fa fa-pencil'></i>", [
                            "class" => "mr-1 mb-1 btn btn-warning",
                            "title" => "Ubah Data",
                            'onclick' => new \yii\web\JsExpression("openmodal( '" . \yii\helpers\Url::to(["/proyek-keuangan-keluar/update-po", "id" => $model->id]) . "',  'Ubah Data PO')")
                        ]);
                    },
                    'delete' => function ($url, $model, $key) {
                        return Html::a("<i class='fa fa-trash'></i>", ["/proyek-keuangan-keluar/delete", "id" => $model->id], [
                            "class" => "mr-1 mb-1 btn btn-danger",
                            "title" => "Hapus",
                            "data-confirm" => "Apakah Anda yakin ingin menghapus data ini ?",
                        ]);
                    },
                ]
            ]),
            // [
            //     'attribute' => 'tipe',
            //     'format' => 'text',
            // ],
            // [
            //     'attribute' => 'status',
            //     'format' => 'text',
            // ],
            // [
            //     'attribute' => 'no_po',
            //     'format' => 'text',
            // ],
            // [
            //     'attribute' => 'dokumen_po',
            //     'format' => 'text',
            // ],
        ],
    ]); ?>
</div>
<?php \yii\widgets\Pjax::end() ?>