<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\assets\MapAsset;
use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;
use kartik\depdrop\DepDrop;
use richardfan\widget\JSRegister;
use yii\web\JsExpression;

/**
 * @var yii\web\View $this
 * @var app\models\IsianLanjutan $model
 * @var app\components\annex\ActiveForm $form
 */
MapAsset::register($this);
?>

<?php $form = ActiveForm::begin([
    'id' => 'IsianLanjutan',
    'layout' => 'horizontal',
    'enableClientValidation' => false,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>
<style>
    #map_canvas {
        width: 100%;
        height: 70vh;
        margin-bottom: 1rem;
        border-radius: 20px;
        box-shadow: 0 8px 4px 5px #eee;
    }
</style>
<div class="row">
    <div class="col-lg-6 col-md-12">
        <h4>Informasi Data Pelanggan</h4>
        <div class="card m-b-30">
            <div class="card-body">
                <div class="d-flex  flex-wrap">
                    <?= $this->render('_form_umum', compact('form', 'model')) ?>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-12">
        <h4>Data Ruangan</h4>
        <div class="card m-b-30">
            <div class="card-body">
                <div class="d-flex  flex-wrap">
                    <?= $this->render('_form_ruangan', compact('form', 'model')) ?>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <h4>Informasi Alamat</h4>
        <div class="card m-b-30">
            <div class="card-body">
                <div class="d-flex  flex-wrap">
                    <?= $this->render('_form_wilayah', compact('form', 'model')) ?>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <h4>Posisi Proyek</h4>
        <div class="card m-b-30">
            <div class="card-body">
                <div class="d-flex  flex-wrap">
                    <?= $form->field($model, 'latitude', ['template' => '{input}'])->hiddenInput(['maxlength' => true])->label(false) ?>
                    <?= $form->field($model, 'longitude', ['template' => '{input}'])->hiddenInput(['maxlength' => true])->label(false) ?>
                    <b>Cari Lokasi</b> : <br><input id="searchTextField" class="form-control" type="text" size="50" style="text-align: left;width:100%;direction: ltr;margin-bottom:1rem;">
                    <div id="map_canvas"></div>
                    <div class="clearfix"></div>
                    <?= $form->field($model, 'alamat_proyek', \app\components\Constant::COLUMN(1))->textArea(['maxlength' => true, 'rows' => 6])->label(false) ?>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <h4>Informasi Tanah</h4>
        <div class="card m-b-30">
            <div class="card-body">
                <div class="d-flex  flex-wrap">
                    <?= $this->render('_form_isian', compact('form', 'model')) ?>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-md-12">
        <div class="card m-b-30">
            <div class="card-body">
                <div class="row">
                    <div class="col-12 text-center">
                        <?= Html::button('<i class="fa fa-file-o"></i> Simpan & Copy Link Preview', ['class' => 'btn btn-warning', 'onclick' => new JsExpression("copy2clip(event)")]); ?>
                        <?= Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
                        <?= Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>
<?php ActiveForm::end(); ?>

<?php JSRegister::begin() ?>
<script>
    window.copy2clip = function(e) {
        let data = $(e.target).closest('form').serialize();
        $.ajax({
            url: '<?= \yii\helpers\Url::to(['/isian-lanjutan/save-and-copy', 'id' => $model->id]) ?>',
            type: 'POST',
            data: data,
            success: function(data) {
                if (data.success) {
                    if (navigator && navigator.clipboard) { // need to check because it's only available on https and localohost
                        navigator.clipboard.writeText(data.data);
                        alert('Link Berhasil Disalin');
                    } else {
                        alert('Salin Link tidak Support di Browser ini. Silahkan Copy Link Manual :' + data.link);
                    }
                } else {
                    alert(data.message);
                }
            },
            error: function(data) {
                // console.log(data.responseJSON.message)
                alert(data.responseJSON.message);
            }
        });
    }
</script>

<?php JSRegister::end() ?>


<?php
// $this->registerJsFile("@web/homepage/vendor/jquery-3.2.1.min.js", ['position' => \yii\web\View::POS_END]);
$js = <<<JS
$(function() {
let id_lat = $('#isianlanjutan-latitude'),
    id_lng = $('#isianlanjutan-longitude'),
    lat = (id_lat.val() != "") ? id_lat.val() : -7.2674864,
    lng = (id_lng.val() != "")  ? id_lng.val() : 112.752035,
    latlng = new google.maps.LatLng(lat, lng);
let mapOptions = {
        center: new google.maps.LatLng(lat, lng),
        zoom: 10,
        mapTypeId: google.maps.MapTypeId.ROADMAP,
        panControl: true,
        panControlOptions: {
            position: google.maps.ControlPosition.TOP_RIGHT
        },
        zoomControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.LARGE,
            position: google.maps.ControlPosition.TOP_left
        }
    },
    map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions),
    marker = new google.maps.Marker({
        position: latlng,
        map: map,
    });
let input = document.getElementById('searchTextField');
let autocomplete = new google.maps.places.Autocomplete(input, {
    types: ["geocode"]
});
autocomplete.bindTo('bounds', map);
let infowindow = new google.maps.InfoWindow();
google.maps.event.addListener(autocomplete, 'place_changed', function(event) {
        infowindow.close();
        let place = autocomplete.getPlace();
        if (place.geometry.viewport) {
            map.fitBounds(place.geometry.viewport);
        } else {
            map.setCenter(place.geometry.location);
            map.setZoom(17);
        }
        moveMarker(place.name, place.geometry.location);
        id_lat.val(place.geometry.location.lat());
        id_lng.val(place.geometry.location.lng());
        let pass = document.getElementById('searchTextField').value;
        $('#isianlanjutan-alamat_proyek').val(place.formatted_address);
    });
    google.maps.event.addListener(map, 'click', function(event) {
        id_lat.val(event.latLng.lat());
        id_lng.val(event.latLng.lng());
        infowindow.close();
        let geocoder = new google.maps.Geocoder();
        geocoder.geocode({
            "latLng": event.latLng
        }, function(results, status) {
            
            if (status == google.maps.GeocoderStatus.OK) {
                
                let lat = results[0].geometry.location.lat(),
                    lng = results[0].geometry.location.lng(),
                    placeName = results[0].address_components[0].long_name,
                    latlng = new google.maps.LatLng(lat, lng);
                moveMarker(placeName, latlng);
                $("#searchTextField").val(results[0].formatted_address);
                $('#isianlanjutan-alamat_proyek').val(results[0].formatted_address);
            }
        });
    });
    function moveMarker(placeName, latlng) {
        marker.setPosition(latlng);
        infowindow.setContent(placeName);
        //infowindow.open(map, marker);
    }
});
JS;

$this->registerJs($js);
?>