<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Modal;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\annex\Tabs;
use app\components\Tanggal;

Modal::begin([
    'id' => 'modalku',
    'header' => '<h3>Detail Penawaran</h3>'
]);
echo "<div id='modalContent'></div>";
Modal::end();

/**
 * @var yii\web\View $this
 * @var app\models\IsianLanjutan $model
 */
$label = $model->konsepDesign->nama_konsep . " ( {$model->user->name} / " . Tanggal::toReadableDate($model->created_at, false) . " )";
$this->title = 'Isian Lanjutan : ' . $label;
$this->params['breadcrumbs'][] = ['label' => 'Isian Lanjutan', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$label, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud isian-lanjutan-view">

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>
    <?php if ($model->status != 5 && $model->status != 6) : ?>
        <?= Html::a('Edit Rencana Survey', ['/isian-lanjutan/rencana-survey/', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Edit Rencana Pembangunan', ['/isian-lanjutan/rencana-pembangunan/', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
    <?php endif ?>
    <?php
    // 0=default,
    // 1=user isi,
    // 2=admin survey, 
    // 3=admin isi penawaran, 
    // 4=deal user, 
    // 5=deal admin
    // 6=deal ditolak
    if ($model->status == 5) {
        echo Html::a('Setujui Rencana Pembangunan', ['/isian-lanjutan/deal-pembangunan/', 'id' => $model->id], ['class' => 'btn btn-success']);
    }
    echo " ";
    if ($model->status == 5 && $model->status != 6) {
        echo Html::a('Tolak Rencana Pembangunan', ['/isian-lanjutan/tolak-pembangunan/', 'id' => $model->id], ['class' => 'btn btn-danger']);
    }
    ?>

    <?= $this->render('_view_info', compact('model')) ?>


    <div class="row">
        <div class="col-md-12">
            <h3>Daftar Penawaran</h3>
            <div class="card m-b-30">
                <div class="card-body">

                    <?php if ($model->status <= 3) : ?>
                        <?= Html::a('Tambahkan Penawaran', ['/penawaran/create', "Penawaran" => ['id_isian_lanjutan' => $model->id]], ['class' => 'btn btn-primary']) ?>
                    <?php endif ?>
                    <?= $this->render('_view_penawaran', compact('model')) ?>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
$script = <<<JS
$(function(){
    
	$('.modalButton').click(function (){
        console.log($(this).attr('value'));
		$('#modalku').modal('show')
			.find('#modalContent')
			.load($(this).attr('value'));
	});
});
JS;

$this->registerJs($script);
