<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Modal;
use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\annex\Tabs;
use richardfan\widget\JSRegister;

/**
 * @var yii\web\View $this
 * @var app\models\Proyek $model
 */
$this->title = 'Proyek : ' . $model->nama_proyek;
$this->registerCss("

.overlay {
    position:absolute;
    width:100%;
    height:100%;
    background:rgba(0,0,0,0.4);
}
");
Modal::begin([
    'header' => 'Lihat CCTV',
    'id' => 'modal',
    'size' => 'modal-dialog-centered',
]);
echo "<div class='modalContent text-center'></div>";
Modal::end();

?>
<?php
$setting = \app\models\SiteSetting::find()->all();
?>
<!-- Navigation -->
<section class="navigation">
    <div class="parallax parallax--nav" style="background-image: url(<?= \Yii::$app->request->baseUrl . "/uploads/" . $setting[0]['gambar_header'] ?>);">
        <div class="overlay"></div>
        <div class="container clearfix">
            <div class="row">
                <div class="col-12">
                    <h2>
                        <?= $setting[0]['tagline']; ?>
                    </h2>
                </div>
                <div class="col-12">
                    <p>
                        <?= $setting[0]['tagline2']; ?>
                    </p>
                </div>
                <div class="col-12">
                    <ul class="breadcrumbs ul--inline ul--no-style">
                        <li>
                            <a href="<?= \Yii::$app->request->BaseUrl ?>/home">Home</a>
                        </li>
                        <span>/</span>
                        <li class="active">
                            <a href="<?= \Yii::$app->request->BaseUrl ?>/home/proyek-saya/index">Proyek Saya</a>
                        </li>
                        <span>/</span>
                        <li class="active">
                            <a href="#">Pantau Proyek</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Navigation -->
<!-- Contact content -->
<section class="contact-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title title-3 title--dark">
                    Pantau Proyek
                </h2>
            </div>
            <div class="col-lg-3 col-md-3 pb-3">
                <?= $this->render('_sidemenu', compact('model')) ?>
            </div>
            <div class="col-lg-9 col-md-9">
                <div class="col-lg-12 col-12 layout-spacing">
                    <!-- flash message -->
                    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
                        <span class="alert alert-info alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span></button>
                            <?= \Yii::$app->session->getFlash('deleteError') ?>
                        </span>
                    <?php endif; ?>

                    <?php Pjax::begin(['id' => 'pjax-ProyekCctvs', 'enableReplaceState' => false, 'linkSelector' => '#pjax-ProyekCctvs ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("defrindr")}']]) ?>
                    <?= '<div class="table-responsive">'
                        . \yii\grid\GridView::widget([
                            'layout' => '{summary}<br/>{items}{pager}',
                            'dataProvider' => new \yii\data\ActiveDataProvider([
                                'query' => $model->getProyekCctvs()->andWhere(['tipe' => \app\models\ProyekCctv::INTERNAL_LINK]),
                                'pagination' => [
                                    'pageSize' => 10,
                                    'pageParam' => 'page-proyekCctvs',
                                ]
                            ]),
                            'pager'        => [
                                'class'          => \app\components\frontend\LinkPager::className(),
                                'firstPageLabel' => 'First',
                                'lastPageLabel'  => 'Last'
                            ],
                            'columns' => [
                                'lokasi',
                                [
                                    'attribute' => 'link',
                                    'format' => 'raw',
                                    'value' => function ($model) {
                                        return
                                            Html::button('Lihat CCTV', ['value' => Url::to('lihat-cctv?id=' . $model->id), 'class' => 'btn btn-success modalButton', 'id' => 'modalButton']);
                                    }
                                ],
                            ]
                        ])
                        . '</div>' ?>
                    <?php Pjax::end() ?>
                </div>
            </div>
        </div>
    </div>
</section>

<?php
$script = <<<JS
$(function(){
	$('.modalButton').click(function (){
		$('#modal').modal('show')
			.find('.modalContent')
			.load($(this).attr('value'));
	});
});
JS;

$this->registerJs($script);
?>