<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use app\components\annex\Alert;
use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\annex\Tabs;
use richardfan\widget\JSRegister;

/**
 * @var yii\web\View $this
 * @var app\models\Proyek $model
 */
$this->registerCssFile("@web/homepage/css/card.css");
$this->registerCssFile("@web/homepage/css/sweetalert2.min.css");
$this->registerCssFile("@web/homepage/charts/apexcharts.css");
$this->registerJsFile("//maps.googleapis.com/maps/api/js?key=AIzaSyAjKSlPBmdJkSO1BY6Qt9gWBlmgVw6KXO4&libraries=places&region=id&language=en");

$this->title = 'Proyek : ' . $model->nama_proyek;
$this->registerCss("

.overlay {
    position:absolute;
    width:100%;
    height:100%;
    background:rgba(0,0,0,0.4);
}

");
?>
<style>
    #map_canvas {
        width: 100%;
        height: 70vh;
        margin-bottom: 1rem;
        border-radius: 20px;
        box-shadow: 0 8px 4px 5px #eee;
    }

    .iconproyek {
        margin: auto;
        display: block;
        background-color: #ebcd1e;
        border-radius: 100%;
        width: 120px;
        height: 120px;
        text-align: center
    }
</style>
<?php JSRegister::begin(); ?>
<script>
    <?php

    $lat = ($model->latitude_proyek) ? $model->latitude_proyek : 0;
    $long = ($model->longitude_proyek) ? $model->longitude_proyek : 0;
    ?>

    $(function() {
        let lat = <?= $lat ?>,
            lng = <?= $long ?>,
            latlng = new google.maps.LatLng(lat, lng);
        let mapOptions = {
                center: new google.maps.LatLng(lat, lng),
                zoom: 10,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
                panControl: true,
                panControlOptions: {
                    position: google.maps.ControlPosition.TOP_RIGHT
                },
                zoomControl: true,
                zoomControlOptions: {
                    style: google.maps.ZoomControlStyle.LARGE,
                    position: google.maps.ControlPosition.TOP_left
                }
            },
            // mebuat konten untuk info window
            contentString = '<p><h4><?= $model->nama_proyek ?></h4></p><p><h5><?= $model->deskripsi_proyek ?></h5></p>';
        // membuat objek info window
        var infowindow = new google.maps.InfoWindow({
            content: contentString,
        });

        map = new google.maps.Map(document.getElementById('map_canvas'), mapOptions),
            marker = new google.maps.Marker({
                position: latlng,
                map: map,
                icon: '<?= \Yii::$app->request->baseUrl . "/uploads/house-icon.png" ?>'
            });
        // event saat marker diklik
        marker.addListener('click', function() {
            // tampilkan info window di atas marker
            infowindow.open(map, marker);
        });
    });
    $(function() {

        $('.modalButton').click(function() {
            console.log($(this).attr('value'));
            $('#modal').modal('show')
                .find('#modalContent')
                .load($(this).attr('value'));
        });
    })
</script>
<?php JSRegister::end(); ?>

<?php
$setting = \app\models\SiteSetting::find()->all();
?>
<!-- Navigation -->
<section class="navigation">
    <div class="parallax parallax--nav" style="background-image: url(<?= \Yii::$app->request->baseUrl . "/uploads/" . $setting[0]['gambar_header'] ?>);">
        <div class="overlay"></div>
        <div class="container clearfix">
            <div class="row">
                <div class="col-12">
                    <h2>
                        <?= $setting[0]['tagline']; ?>
                    </h2>
                </div>
                <div class="col-12">
                    <p>
                        <?= $setting[0]['tagline2']; ?>
                    </p>
                </div>
                <div class="col-12">
                    <ul class="breadcrumbs ul--inline ul--no-style">
                        <li>
                            <a href="<?= \Yii::$app->request->BaseUrl ?>/home">Home</a>
                        </li>
                        <span>/</span>
                        <li class="active">
                            <a href="<?= \Yii::$app->request->BaseUrl ?>/home/proyek-saya/index">Proyek Saya</a>
                        </li>
                        <span>/</span>
                        <li class="active">
                            <a href="#">Detail Proyek</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- End Navigation -->
<!-- Contact content -->
<section class="contact-content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <h2 class="title title-3 title--dark">
                    Detail Proyek
                </h2>

            </div>
            <div class="col-lg-3 col-md-3 pb-3">
                <?= $this->render('_sidemenu', compact('model')) ?>
            </div>
            <div class="col-lg-9 col-md-9">
                <?= Alert::widget() ?>
                <div class="col-lg-12 col-12 layout-spacing">
                    <div class="row">
                        <div class="col-md-12 col-sm-12">
                            <div class="card m-b-30">
                                <div class="card-body">
                                    <?php $this->beginBlock('app\models\Proyek') ?>
                                    <div style="margin: 1.5rem;"></div>
                                    <div class="row">
                                        <div class="col-12">
                                            <div class="row">
                                                <div class="col-12">
                                                    <div class="cardx cardx-1 text-center">
                                                        <div class="cardx__icon"><i class="fa fa-building"></i>
                                                            <span class="font-weight-bold" style="font-size: 1rem;">
                                                                <?= $model->nama_proyek ?>
                                                            </span>
                                                        </div>
                                                        <p class="cardx__title text-center"><?= $model->deskripsi_proyek ?></p>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                                    <div class="cardx cardx-2 text-center">
                                                        <div class="cardx__icon"><i class="fa fa-dollar"></i>
                                                            <span class="font-weight-bold" style="font-size: 1rem;">Realisasi Dana</span>
                                                        </div>
                                                        <div class="cardx__title text-center">
                                                            <div class="row mx-auto">
                                                                <div class="col-6">
                                                                    <p class="text-left ml-2">Total Anggaran</p>
                                                                </div>
                                                                <div class="col-6">
                                                                    <p class="text-right mr-2"><?= $model->getTotalAnggaran() ?></p>
                                                                </div>
                                                                <div class="col-6">
                                                                    <p class="text-left ml-2">Total Pengeluaran</p>
                                                                </div>
                                                                <div class="col-6">
                                                                    <p class="text-right mr-2"><?= $model->getTotalPengeluaran() ?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-6 col-md-6 col-sm-12 col-12">
                                                    <div class="cardx cardx-3 text-center">
                                                        <div class="cardx__icon"><i class="fa fa-clock-o"></i>
                                                            <span class="font-weight-bold" style="font-size: 1rem;">Sisa Waktu</span>
                                                        </div>
                                                        <div class="cardx__title text-center">
                                                            <div class="row">
                                                                <div class="col-12">
                                                                    <p class=""><?= $model->getSisaHari() ?> Hari</p>
                                                                </div>
                                                                <div class="col-12">
                                                                    <p class="">
                                                                        <?= Yii::$app->formatter->asIddate($model->tanggal_awal_kontrak) ?>
                                                                        -
                                                                        <?= Yii::$app->formatter->asIddate($model->tanggal_akhir_kontrak) ?>
                                                                    </p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4 col-md-4 col-sm-12 col-12">
                                                    <div class="cardx cardx-4 text-center" style="min-height: 120px;">
                                                        <div class="cardx__icon mt-3"><i class="fa fa-money"></i>
                                                            <span class="font-weight-bold" style="font-size: 1rem;">Nilai Kontrak</span>
                                                        </div>
                                                        <div class="cardx__title text-center mt-3">
                                                            <div class="row">
                                                                <div class="col-12">
                                                                    <p class=""><?= \Yii::$app->formatter->asRp($model->nilai_kontrak) ?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4 col-md-4 col-sm-12 col-12">
                                                    <div class="cardx cardx-1 text-center" style="min-height: 120px;">
                                                        <div class="cardx__icon"><i class="fa fa-bar-charts"></i>
                                                            <span class="font-weight-bold" style="font-size: 1rem;">Deviasi Progress</span>
                                                        </div>
                                                        <div class="cardx__title text-center">
                                                            <div class="row mx-auto">
                                                                <div class="col-8">
                                                                    <p class="text-left ml-4">Week Period</p>
                                                                </div>
                                                                <div class="col-4">
                                                                    <p class="text-left"><?= round($progress_minggu_ini['data'], 2) ?> %</p>
                                                                </div>
                                                                <div class="col-8">
                                                                    <p class="text-left ml-4">Deviasi</p>
                                                                </div>
                                                                <div class="col-4">
                                                                    <p class="text-left"><?= round($progress_minggu_ini['deviasi'], 2) ?> %</p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-4 col-md-4 col-sm-12 col-12">
                                                    <div class="cardx cardx-5 text-center" style="min-height: 120px;">
                                                        <div class="cardx__icon mt-3"><i class="fa fa-hourglass-half"></i>
                                                            <span class="font-weight-bold" style="font-size: 1rem;">Realisasi Proyek</span>
                                                        </div>
                                                        <div class="cardx__title text-center mt-3">
                                                            <div class="row">
                                                                <div class="col-12">
                                                                    <p class=""><?= $model->getRealisasiProyek() ?></p>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="col-lg-12 mt-4">
                                                    <div id="chart" style="width: calc(100% / 1 - 15px);">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>

                                    <?php $this->endBlock() ?>
                                    <?php $this->beginBlock('Map') ?>

                                    <div id="map_canvas"></div>
                                    <?php $this->endBlock() ?>

                                    <?= Tabs::widget(
                                        [
                                            'id' => 'relation-tabs',
                                            'encodeLabels' => false,
                                            'linkOptions' => [
                                                'class' => 'nav-link',
                                                'style' => '
                                            border: groove;
                                            border-color: #239ade;
                                            border-top: 10px;
                                            border-left: 0px;
                                            border-right: 0px;
                                        ',
                                            ],
                                            'items' => [
                                                [
                                                    'label'   => '<b>Detail Proyek</b>',
                                                    'content' => $this->blocks['app\models\Proyek'],
                                                    'active'  => true,
                                                ],
                                                [
                                                    'content' => $this->blocks['Map'],
                                                    'label'   => 'Lokasi Proyek',
                                                    'active'  => false,
                                                ],
                                            ]
                                        ]
                                    );
                                    ?>
                                    <hr />

                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6 col-sm-12 mb-3">
                            <h4>Dokumen & Desain</h4>
                            <div class="m-b-30">
                                <div class="">
                                    <?= $this->render('_dokumen', compact('model')) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 mb-3">
                            <h4>Galeri</h4>
                            <div class="m-b-30">
                                <div class="">
                                    <?= $this->render('_galeri', compact('model')) ?>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <h4>Progress</h4>
                            <div class="card m-b-30">
                                <div class="card-body">
                                    <?= $this->render("_progress.php", compact('model')) ?>
                                </div>
                            </div>
                        </div>
                        <?php if ($model->status == 1) : ?>
                            <div class="col-12 text-center">
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#revisi">
                                    Revisi / Selesai
                                </button>

                                <!-- Modal -->
                                <div class="modal fade" id="revisi" tabindex="-1" role="dialog" aria-labelledby="revisi" aria-hidden="true">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="revisi">Apakah Ada Revisi?</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                Jika ada revisi, klik tombol revisi. Jika tidak ada maka Anda dapat me-konfirmasi proyek selesai. </div>
                                            <div class="modal-footer">
                                                <div class="row" style="width: 100%;">
                                                    <div class="col-6">
                                                        <?= Html::a('Proyek Selesai', ['proyek-selesai', 'id' => $model->kode_unik], ['class' => 'btn btn-block btn-info text-white']); ?>
                                                    </div>
                                                    <div class="col-6">
                                                        <?= Html::a('Revisi', ['revisi-proyek', 'id' => $model->kode_unik], ['class' => 'btn btn-block btn-warning']); ?>
                                                    </div>
                                                </div>
                                                <!-- <button type="button" class="btn btn-secondary" data-dismiss="modal">Tutup</button> -->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <?php endif ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php
// $this->registerJsFile("@web/homepage/charts/apexcharts.js");
?>
<?php JSRegister::begin(); ?>
<script>
    var options = {
        chart: {
            height: 452,
            width: "100%",
            toolbar: {
                show: !1
            },
            type: "area",
            toolbar: {
                show: true,
                tools: {
                    download: true,
                    selection: true,
                    zoom: true,
                    zoomin: true,
                    zoomout: true,
                    pan: true,
                    reset: true
                },
                autoSelected: "zoom"
            },
            zoom: {
                enabled: true,
                type: 'x',
                autoScaleYaxis: true,
                zoomedArea: {
                    fill: {
                        color: '#90CAF9',
                        opacity: 0.4
                    },
                    stroke: {
                        color: '#0D47A1',
                        opacity: 0.4,
                        width: 1
                    }
                }
            }
        },
        stroke: {
            curve: "straight",
            width: [4, 4]
        },
        grid: {
            borderColor: "#d5d5d5"
        },
        legend: {
            show: !1
        },
        colors: ['#b84644', '#45A387'],
        fill: {
            type: "solid",
        },
        dataLabels: {
            enabled: true,
            enabledOnSeries: undefined,
            formatter: function(val, opts) {
                return val
            },
            textAnchor: 'middle',
            distributed: false,
            offsetX: 0,
            offsetY: 0,
            style: {
                fontSize: '14px',
                fontFamily: 'Helvetica, Arial, sans-serif',
                fontWeight: 'bold',
                colors: undefined
            },
            background: {
                enabled: false,
                foreColor: '#fff',
                padding: 4,
                borderRadius: 2,
                borderWidth: 1,
                borderColor: '#fff',
                opacity: 0.9,
                dropShadow: {
                    enabled: false,
                    top: 1,
                    left: 1,
                    blur: 1,
                    color: '#000',
                    opacity: 0.45
                }
            },
            dropShadow: {
                enabled: false,
                top: 1,
                left: 1,
                blur: 1,
                color: '#000',
                opacity: 0.45
            }
        },
        markers: {
            size: 0,
            hover: {
                size: 5
            }
        },
        fill: {
            type: 'gradient',
            gradient: {
                opacityFrom: 0.6,
                opacityTo: 0.1,
            }
        },
        legend: {
            position: 'bottom',
            horizontalAlign: 'center'
        },
        xaxis: {
            type: 'datetime',
            labels: {
                style: {
                    colors: "#000"
                }
            },
            axisTicks: {
                show: !1,
            },
            categories: <?= $daftar_tanggal  ?>,
            axisBorder: {
                show: !1
            },
            tickPlacement: "on"
        },
        yaxis: {
            tickAmount: 5,
            max: 100,
            labels: {
                style: {
                    color: "#000"
                },
            },
            title: {
                text: '%',
            },
        },
        tooltip: {
            x: {
                format: 'dd/MM/yy'
            },
        },
        series: [{
            name: 'Target Progress',
            data: <?= $target_perminggu ?>
        }, {
            name: 'Progress',
            data: <?= $progress_perminggu ?>
        }],
    };

    var chart = new ApexCharts(document.querySelector("#chart"), options);
    chart.render();
</script>
<?php JSRegister::end(); ?>