<?php

/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\ProfileTukangSearch $searchModel
 */

$this->title = 'Profile Tukang';
$this->params['breadcrumbs'][] = $this->title;
?>


<?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']]) ?>

<div class="row">
    <div class="col-md-12">
        <div class="card mb-3">
            <div class="card-body">
                <div class="table-responsive">
                    <?= GridView::widget([
                        'layout' => '{summary}{pager}{items}{pager}',
                        'dataProvider' => $dataProvider,
                        'pager'        => [
                            'class'          => app\components\annex\LinkPager::className(),
                            'firstPageLabel' => 'First',
                            'lastPageLabel'  => 'Last'
                        ],
                        'filterModel' => $searchModel,
                        'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                        'headerRowOptions' => ['class' => 'x'],
                        'columns' => [

                            \app\components\ActionButton::getButtons(
                                [
                                    'template' => '{approve} {activate} {nonactivate} {view}',
                                    'buttons' => [
                                        'approve' => function ($url, $model, $key) {
                                            if ($model->status != 0) {
                                                return '';
                                            }
                                            return Html::a('<i class="fa fa-check"></i>', $url, [
                                                'title' => 'Approve',
                                                'class' => 'btn mr-1 mb-1 btn-primary',
                                                'data-confirm' => 'Apakah anda yakin akan meng-approve data ini?',
                                                'data-method' => 'post',
                                                'data-pjax' => '0',
                                            ]);
                                        },
                                        'activate' => function ($url, $model, $key) {
                                            if ($model->status == 0 || $model->status == 1) {
                                                return '';
                                            }
                                            return Html::a('<i class="fa fa-check"></i>', $url, [
                                                'title' => 'Active',
                                                'class' => 'btn mr-1 mb-1 btn-success',
                                                'data-confirm' => 'Apakah anda yakin akan meng-active data ini?',
                                                'data-method' => 'post',
                                                'data-pjax' => '0',
                                            ]);
                                        },
                                        'nonactivate' => function ($url, $model, $key) {
                                            if ($model->status == 0 || $model->status == 2) {
                                                return '';
                                            }
                                            return Html::a('<i class="fa fa-times"></i>', $url, [
                                                'title' => 'Nonactive',
                                                'class' => 'btn mr-1 mb-1 btn-danger',
                                                'data-confirm' => 'Apakah anda yakin akan meng-nonactive data ini?',
                                                'data-method' => 'post',
                                                'data-pjax' => '0',
                                            ]);
                                        },

                                    ]
                                ]
                            ),

                            // modified by Defri Indra
                            // [
                            //     'class' => yii\grid\DataColumn::className(),
                            //     'attribute' => 'id_user',
                            //     'value' => function ($model) {
                            //         if ($rel = $model->user) {
                            //             return $rel->name;
                            //         } else {
                            //             return '';
                            //         }
                            //     },
                            //     'format' => 'raw',
                            // ],
                            [
                                'attribute' => 'nama',
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'email',
                                'value' => function ($model) {
                                    if ($rel = $model->user) {
                                        return $rel->email;
                                    } else {
                                        return '';
                                    }
                                },
                            ],
                            [
                                'attribute' => 'no_hp',
                                'value' => function ($model) {
                                    if ($rel = $model->user) {
                                        return $rel->no_hp;
                                    } else {
                                        return '';
                                    }
                                },
                            ],
                            [
                                'attribute' => 'foto_ktp',
                                'filter' => false,
                                'format' => 'myImage',
                            ],
                            [
                                'attribute' => 'keahlian',
                                'filter' => false,
                                'format' => 'text',
                            ],
                            [
                                'attribute' => 'alamat',
                                'filter' => false,
                                'format' => 'ntext',
                            ],
                            [
                                'attribute' => 'status',
                                'format' => 'boolean',
                            ],
                            // modified by Defri Indra
                            [
                                'class' => yii\grid\DataColumn::className(),
                                'attribute' => 'id_layanan',
                                'filter' => false,
                                'value' => function ($model) {
                                    return $model->getLayananLabel();
                                },
                                'format' => 'raw',
                            ],
                        ],
                    ]); ?>
                </div>
            </div>
        </div>
    </div>
</div>
<?php \yii\widgets\Pjax::end() ?>