<?php
/**
 * Autogenerated From GII
 * modified by Defri Indra M
 * 2021
 */

use yii\helpers\Html;
use app\components\annex\ActiveForm;
use \app\components\annex\Tabs;

/**
* @var yii\web\View $this
* @var app\models\SupplierOrderDetail $model
* @var app\components\annex\ActiveForm $form
*/

?>

<?php $form = ActiveForm::begin([
    'id' => 'SupplierOrderDetail',
    'layout' => 'horizontal',
    'enableClientValidation' => true,
    'errorSummaryCssClass' => 'error-summary alert alert-error'
]);
?>
<?php echo $form->errorSummary($model); ?>

<div class="clearfix"></div>
<div class="d-flex  flex-wrap">

	<?= $form->field($model, 'kode_unik', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
	<?=         // modified by Defri Indra
        $form->field($model, 'supplier_order_id', \app\components\Constant::COLUMN())->widget(\kartik\select2\Select2::classname(), [
            'name' => 'class_name',
            'model' => $model,
            'attribute' => 'supplier_order_id',
            'data' => \yii\helpers\ArrayHelper::map(app\models\SupplierOrder::find()->all(), 'id', 'id'),
            'options' => [
                'placeholder' => $model->getAttributeLabel('supplier_order_id'),
                'multiple' => false,
                'disabled' => (isset($relAttributes) && isset($relAttributes['supplier_order_id'])),
            ]
        ]); ?>
	<?= $form->field($model, 'kode_order', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
	<?=         // modified by Defri Indra
        $form->field($model, 'supplier_barang_id', \app\components\Constant::COLUMN())->widget(\kartik\select2\Select2::classname(), [
            'name' => 'class_name',
            'model' => $model,
            'attribute' => 'supplier_barang_id',
            'data' => \yii\helpers\ArrayHelper::map(app\models\SupplierBarang::find()->all(), 'id', 'id'),
            'options' => [
                'placeholder' => $model->getAttributeLabel('supplier_barang_id'),
                'multiple' => false,
                'disabled' => (isset($relAttributes) && isset($relAttributes['supplier_barang_id'])),
            ]
        ]); ?>
	<?= $form->field($model, 'jumlah', \app\components\Constant::COLUMN())->textInput() ?>
	<?= $form->field($model, 'total_ppn', \app\components\Constant::COLUMN())->textInput() ?>
	<?= $form->field($model, 'catatan', \app\components\Constant::COLUMN())->textarea(['rows' => 6]) ?>
	<?= $form->field($model, 'voucher', \app\components\Constant::COLUMN())->textInput(['maxlength' => true]) ?>
    <div class="clearfix"></div>
</div>
<hr/>
<div class="row">
    <div class="col-md-offset-3 col-md-10">
        <?=  Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']); ?>
        <?=  Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default']) ?>
    </div>
</div>
<?php ActiveForm::end(); ?>